import type { ApiError, Track, TranscriptResponse, Segment } from "@/types/transcript";
import type { FetchTranscriptOptions, TranscriptProvider } from "./types";
import { parseVtt } from "@/lib/parseVtt";

interface VimeoTextTrack {
  id: number;
  lang: string;
  url: string;
  kind: string;
  label: string;
}

interface VimeoPlayerConfig {
  video?: { id?: number; title?: string; duration?: number };
  request?: { text_tracks?: VimeoTextTrack[] };
}

function extractConfigFromPageData(pageData: unknown): VimeoPlayerConfig | null {
  if (!pageData || typeof pageData !== "object") return null;
  const obj = pageData as Record<string, unknown>;
  // Content script sends the raw config object
  if (obj["video"] || obj["request"]) return pageData as VimeoPlayerConfig;
  return null;
}

async function fetchPlayerConfig(videoId: string): Promise<VimeoPlayerConfig | ApiError> {
  try {
    const res = await fetch(`https://player.vimeo.com/video/${videoId}/config`, {
      headers: { "Referer": `https://vimeo.com/${videoId}` },
    });
    if (res.status === 404) return { error: "invalid_id", message: "Video not found on Vimeo." };
    if (res.status === 403) return { error: "unavailable", message: "This Vimeo video is private or restricted." };
    if (!res.ok) return { error: "fetch_failed", message: `Vimeo config HTTP ${res.status}` };
    return await res.json() as VimeoPlayerConfig;
  } catch (e) {
    return { error: "fetch_failed", message: e instanceof Error ? e.message : String(e) };
  }
}

function mapTracks(textTracks: VimeoTextTrack[]): Track[] {
  return textTracks.map((t) => ({
    languageCode: t.lang,
    name: t.label || t.lang,
    kind: t.kind === "captions" ? undefined : t.kind,
  }));
}

async function fetchVttSegments(trackUrl: string): Promise<Segment[] | ApiError> {
  // Vimeo VTT URLs are relative to player.vimeo.com
  const resolvedUrl = trackUrl.startsWith("http")
    ? trackUrl
    : `https://player.vimeo.com${trackUrl}`;

  try {
    const res = await fetch(resolvedUrl);
    if (!res.ok) return { error: "fetch_failed", message: `VTT fetch HTTP ${res.status}` };
    const vttText = await res.text();
    const segments = parseVtt(vttText);
    if (segments.length === 0) return { error: "no_captions", message: "Transcript is empty." };
    return segments;
  } catch (e) {
    return { error: "fetch_failed", message: e instanceof Error ? e.message : String(e) };
  }
}

export class VimeoProvider implements TranscriptProvider {
  readonly platform = "vimeo" as const;

  async fetchTranscript(videoId: string, options?: FetchTranscriptOptions): Promise<TranscriptResponse | ApiError> {
    // Layer 1: Use page-extracted config if available
    let config: VimeoPlayerConfig | ApiError | null = null;
    if (options?.pageData) {
      config = extractConfigFromPageData(options.pageData);
    }

    // Layer 2: Fetch config from player endpoint
    if (!config) {
      config = await fetchPlayerConfig(videoId);
    }
    if ("error" in config) return config;

    const textTracks = config.request?.text_tracks ?? [];
    if (textTracks.length === 0) {
      return { error: "no_captions", message: "This video has no captions available." };
    }

    // Select requested language or default to first track
    const track = options?.lang
      ? (textTracks.find((t) => t.lang === options.lang) ?? textTracks[0]!)
      : textTracks[0]!;

    const segments = await fetchVttSegments(track.url);
    if ("error" in segments) return segments;

    const title = config.video?.title ?? "Untitled";
    const isAutoGenerated = track.lang.includes("autogen") || track.label.toLowerCase().includes("auto");

    return {
      videoId,
      title,
      language: track.lang.replace("-x-autogen", ""),
      isAutoGenerated,
      tracks: mapTracks(textTracks),
      segments,
    };
  }

  async fetchTracks(videoId: string, pageData?: unknown): Promise<{ tracks: Track[]; title: string } | ApiError> {
    let config: VimeoPlayerConfig | ApiError | null = null;
    if (pageData) {
      config = extractConfigFromPageData(pageData);
    }
    if (!config) {
      config = await fetchPlayerConfig(videoId);
    }
    if ("error" in config) return config;

    const textTracks = config.request?.text_tracks ?? [];
    if (textTracks.length === 0) {
      return { error: "no_captions", message: "This video has no captions available." };
    }

    return {
      tracks: mapTracks(textTracks),
      title: config.video?.title ?? "Untitled",
    };
  }
}
