import type {Segment} from "../types/transcript";
import {sanitizeFilename} from "./sanitizeFilename";

function triggerDownload(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], {type: mimeType});
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

interface ExportJsonOptions {
    videoId: string;
    title: string;
    language: string;
    isAutoGenerated: boolean;
    segments: Segment[];
    sourceUrl?: string;
}

interface JsonSegment {
    start: number;
    end: number;
    text: string;
}

interface JsonExport {
    videoId: string;
    title: string;
    url?: string;
    language: string;
    isAutoGenerated: boolean;
    extractedAt: string;
    segments: JsonSegment[];
}

export function generateJson(options: ExportJsonOptions): string {
    const {videoId, title, language, isAutoGenerated, segments, sourceUrl} = options;

    const output: JsonExport = {
        videoId,
        title,
        ...(sourceUrl ? {url: sourceUrl} : {}),
        language,
        isAutoGenerated,
        extractedAt: new Date().toISOString(),
        segments: segments.map((s) => ({
            start: s.start,
            end: s.start + s.duration,
            text: s.text,
        })),
    };

    return JSON.stringify(output, null, 2);
}

export function exportJson(options: ExportJsonOptions, filename?: string): void {
    const content = generateJson(options);
    const name = filename ?? sanitizeFilename(options.title, options.language, "json");
    triggerDownload(content, name, "application/json;charset=utf-8");
}
