/**
 * Wire schemas for everything that crosses chrome.runtime messaging.
 *
 * The background and the side panel validate incoming messages and replies
 * with these schemas, and the TypeScript types are inferred from them so a
 * shape is written once. Content scripts must not import this module: they
 * run in every frame of a page and only need the types, which they take from
 * src/types via type-only re-exports.
 */
import { z } from "zod";
import { TIMED_TEXT_FORMATS } from "../timed-text/detect";

// ---------- transcript domain ----------

export const segmentSchema = z.object({
  start: z.number(),
  duration: z.number(),
  text: z.string(),
});

export const chapterSchema = z.object({
  title: z.string(),
  start: z.number(),
});

export const trackSchema = z.object({
  id: z.string().optional(),
  languageCode: z.string(),
  name: z.string(),
  kind: z.string().optional(),
  format: z.string().optional(),
  source: z.string().optional(),
});

export const transcriptSourceSchema = z.enum([
  "page-track",
  "network-resource",
  "platform-adapter",
  "on-device",
]);

export const transcriptResponseSchema = z.object({
  videoId: z.string(),
  title: z.string(),
  language: z.string(),
  isAutoGenerated: z.boolean(),
  tracks: z.array(trackSchema),
  segments: z.array(segmentSchema),
  chapters: z.array(chapterSchema).optional(),
  translatedFrom: z.string().optional(),
  translatedTo: z.string().optional(),
  pageUrl: z.string().optional(),
  source: transcriptSourceSchema.optional(),
});

export const apiErrorSchema = z.object({
  error: z.enum([
    "no_captions",
    "invalid_id",
    "unavailable",
    "rate_limited",
    "fetch_failed",
    "invalid_request",
    "transcription_failed",
  ]),
  message: z.string(),
});

export const platformSchema = z.enum(["web", "youtube"]);

const videoListSchema = z.array(
  z.object({ videoId: z.string(), title: z.string(), duration: z.string() }),
);

export const playlistResponseSchema = z.object({
  playlistTitle: z.string(),
  videos: videoListSchema,
});

export const channelResponseSchema = z.object({
  channelTitle: z.string(),
  videos: videoListSchema,
});

const errorReplySchema = z.object({ error: z.string() });

export const playlistReplySchema = z.union([playlistResponseSchema, errorReplySchema]);
export const channelReplySchema = z.union([channelResponseSchema, errorReplySchema]);

export type Segment = z.infer<typeof segmentSchema>;
export type Chapter = z.infer<typeof chapterSchema>;
export type Track = z.infer<typeof trackSchema>;
export type TranscriptResponse = z.infer<typeof transcriptResponseSchema>;
export type ApiError = z.infer<typeof apiErrorSchema>;
export type Platform = z.infer<typeof platformSchema>;
export type PlaylistResponse = z.infer<typeof playlistResponseSchema>;
export type ChannelResponse = z.infer<typeof channelResponseSchema>;

// ---------- discovery domain ----------

export const timedTextFormatSchema = z.enum(TIMED_TEXT_FORMATS);

export const timedTextSourceSchema = z.enum([
  "runtime",
  "track",
  "fetch",
  "xhr",
  "performance",
  "blob",
  "data",
  "manifest",
]);

export const mediaPlaybackStateSchema = z.object({
  mediaId: z.string(),
  pageUrl: z.string(),
  title: z.string(),
  currentTime: z.number(),
  duration: z.number().nullable(),
  paused: z.boolean(),
  ended: z.boolean(),
  muted: z.boolean(),
  volume: z.number(),
  readyState: z.number(),
});

export const runtimeTextTrackSnapshotSchema = z.object({
  trackId: z.string(),
  mediaId: z.string(),
  language: z.string(),
  label: z.string(),
  kind: z.string(),
  mode: z.enum(["disabled", "hidden", "showing"]),
  sourceUrl: z.string().optional(),
  cues: z.array(segmentSchema),
});

export const timedTextResourceSchema = z.object({
  url: z.string(),
  mimeType: z.string(),
  format: timedTextFormatSchema,
  source: timedTextSourceSchema,
  bodyText: z.string().optional(),
  language: z.string().optional(),
  label: z.string().optional(),
  kind: z.string().optional(),
  trackId: z.string().optional(),
  error: z.string().optional(),
});

export const pageDiscoverySnapshotSchema = z.object({
  pageUrl: z.string(),
  frameUrl: z.string(),
  title: z.string(),
  documentLanguage: z.string(),
  media: z.array(mediaPlaybackStateSchema),
  tracks: z.array(runtimeTextTrackSnapshotSchema),
  requiredOrigins: z.array(z.string()),
});

export const discoveryTargetSchema = z.object({
  tabId: z.number(),
  url: z.string(),
  title: z.string(),
});

export const discoveryDiagnosticsSchema = z.object({
  candidateCount: z.number(),
  detectedFormats: z.array(timedTextFormatSchema),
  hasInBandCaptions: z.boolean(),
  hasUnsupportedTimedText: z.boolean(),
  requiredOrigins: z.array(z.string()),
});

export const discoveryResponseSchema = z.discriminatedUnion("status", [
  discoveryTargetSchema.extend({ status: z.literal("discovering") }),
  discoveryTargetSchema.extend({ status: z.literal("awaiting-action") }),
  z.object({
    status: z.literal("found"),
    target: discoveryTargetSchema,
    data: transcriptResponseSchema,
    diagnostics: discoveryDiagnosticsSchema,
  }),
  z.object({
    status: z.literal("empty"),
    target: discoveryTargetSchema,
    diagnostics: discoveryDiagnosticsSchema,
    media: mediaPlaybackStateSchema.nullable(),
  }),
  z.object({ status: z.literal("idle") }),
  z.object({ status: z.literal("error"), error: z.string() }),
]);

export type TimedTextSource = z.infer<typeof timedTextSourceSchema>;
export type MediaPlaybackState = z.infer<typeof mediaPlaybackStateSchema>;
export type RuntimeTextTrackSnapshot = z.infer<typeof runtimeTextTrackSnapshotSchema>;
export type TimedTextResource = z.infer<typeof timedTextResourceSchema>;
export type PageDiscoverySnapshot = z.infer<typeof pageDiscoverySnapshotSchema>;
export type DiscoveryTarget = z.infer<typeof discoveryTargetSchema>;
export type DiscoveryDiagnostics = z.infer<typeof discoveryDiagnosticsSchema>;
export type DiscoveryResponse = z.infer<typeof discoveryResponseSchema>;

// ---------- tab transcription ----------

export const tabTranscriptionTargetSchema = z.object({
  tabId: z.number(),
  videoId: z.string(),
  title: z.string(),
  url: z.string(),
});

export const tabTranscriptionResponseSchema = z.discriminatedUnion("status", [
  tabTranscriptionTargetSchema.extend({ status: z.literal("started") }),
  tabTranscriptionTargetSchema.extend({ status: z.literal("awaiting-action") }),
  z.object({ status: z.literal("idle") }),
  z.object({ status: z.literal("error"), error: z.string() }),
]);

export type TabTranscriptionTarget = z.infer<typeof tabTranscriptionTargetSchema>;
export type TabTranscriptionResponse = z.infer<typeof tabTranscriptionResponseSchema>;

// ---------- content script -> background ----------

export const playerTimeMessageSchema = z.object({
  type: z.literal("player-time"),
  currentTime: z.number(),
});

export const timedTextPageSnapshotMessageSchema = z.object({
  type: z.literal("timed-text-page-snapshot"),
  snapshot: pageDiscoverySnapshotSchema,
});

export const timedTextResourceMessageSchema = z.object({
  type: z.literal("timed-text-resource"),
  resource: timedTextResourceSchema,
});

export const mediaPlaybackStateMessageSchema = z.object({
  type: z.literal("media-playback-state"),
  state: mediaPlaybackStateSchema,
});

export const interceptedCaptureMessageSchema = z.object({
  type: z.literal("intercepted-capture"),
  kind: z.enum(["player", "timedtext"]),
  videoId: z.string().nullable(),
  url: z.string(),
  status: z.number(),
  bodyText: z.string(),
});

export type PlayerTimeMessage = z.infer<typeof playerTimeMessageSchema>;
export type TimedTextPageSnapshotMessage = z.infer<typeof timedTextPageSnapshotMessageSchema>;
export type TimedTextResourceMessage = z.infer<typeof timedTextResourceMessageSchema>;
export type MediaPlaybackStateMessage = z.infer<typeof mediaPlaybackStateMessageSchema>;
export type InterceptKind = z.infer<typeof interceptedCaptureMessageSchema>["kind"];
export type InterceptedCaptureMessage = z.infer<typeof interceptedCaptureMessageSchema>;

// ---------- side panel -> background ----------

export const fetchTranscriptMessageSchema = z.object({
  type: z.literal("fetch-transcript"),
  videoId: z.string(),
  platform: platformSchema,
  lang: z.string().optional(),
  translateTo: z.string().optional(),
});

export const fetchPlaylistMessageSchema = z.object({
  type: z.literal("fetch-playlist"),
  playlistId: z.string(),
});

export const fetchChannelMessageSchema = z.object({
  type: z.literal("fetch-channel"),
  identifier: z.string(),
});

export const seekToMessageSchema = z.object({
  type: z.literal("seek-to"),
  time: z.number(),
});

export const discoverCurrentTabMessageSchema = z.object({
  type: z.literal("discover-current-tab"),
});

export const rediscoverTabMessageSchema = z.object({
  type: z.literal("rediscover-tab"),
  tabId: z.number(),
});

export const prepareUrlDiscoveryMessageSchema = z.object({
  type: z.literal("prepare-url-discovery"),
  url: z.string(),
});

export const getDiscoveryStateMessageSchema = z.object({
  type: z.literal("get-discovery-state"),
});

export const cancelPendingDiscoveryMessageSchema = z.object({
  type: z.literal("cancel-pending-discovery"),
  tabId: z.number(),
});

export const selectDiscoveredTrackMessageSchema = z.object({
  type: z.literal("select-discovered-track"),
  videoId: z.string(),
  trackId: z.string(),
});

export const startTranscriptionMessageSchema = z.object({
  type: z.literal("start-transcription"),
  videoId: z.string().optional(),
  title: z.string().optional(),
});

export const getTabTranscriptionStateMessageSchema = z.object({
  type: z.literal("get-tab-transcription-state"),
});

export const cancelPendingTranscriptionMessageSchema = z.object({
  type: z.literal("cancel-pending-transcription"),
  tabId: z.number(),
});

export const stopTranscriptionMessageSchema = z.object({
  type: z.literal("stop-transcription"),
});

// The side panel owns the File, mints a blob: URL for it (same extension
// origin as the offscreen document) and passes only the URL: File objects do
// not survive chrome.runtime message serialization.
export const transcribeFileMessageSchema = z.object({
  type: z.literal("transcribe-file"),
  blobUrl: z.string(),
  videoId: z.string(),
  title: z.string(),
});

export type FetchTranscriptMessage = z.infer<typeof fetchTranscriptMessageSchema>;
export type FetchPlaylistMessage = z.infer<typeof fetchPlaylistMessageSchema>;
export type FetchChannelMessage = z.infer<typeof fetchChannelMessageSchema>;
export type SeekToMessage = z.infer<typeof seekToMessageSchema>;
export type DiscoverCurrentTabMessage = z.infer<typeof discoverCurrentTabMessageSchema>;
export type RediscoverTabMessage = z.infer<typeof rediscoverTabMessageSchema>;
export type PrepareUrlDiscoveryMessage = z.infer<typeof prepareUrlDiscoveryMessageSchema>;
export type GetDiscoveryStateMessage = z.infer<typeof getDiscoveryStateMessageSchema>;
export type CancelPendingDiscoveryMessage = z.infer<typeof cancelPendingDiscoveryMessageSchema>;
export type SelectDiscoveredTrackMessage = z.infer<typeof selectDiscoveredTrackMessageSchema>;
export type StartTranscriptionMessage = z.infer<typeof startTranscriptionMessageSchema>;
export type GetTabTranscriptionStateMessage = z.infer<typeof getTabTranscriptionStateMessageSchema>;
export type CancelPendingTranscriptionMessage = z.infer<typeof cancelPendingTranscriptionMessageSchema>;
export type StopTranscriptionMessage = z.infer<typeof stopTranscriptionMessageSchema>;
export type TranscribeFileMessage = z.infer<typeof transcribeFileMessageSchema>;

// ---------- background -> side panel ----------

export const transcriptResultMessageSchema = z.object({
  type: z.literal("transcript-result"),
  data: transcriptResponseSchema,
});

export const transcriptErrorMessageSchema = z.object({
  type: z.literal("transcript-error"),
  error: apiErrorSchema,
});

/** Reply to fetch-transcript and select-discovered-track. */
export const transcriptReplySchema = z.discriminatedUnion("type", [
  transcriptResultMessageSchema,
  transcriptErrorMessageSchema,
]);

// Same payload as transcript-result but a distinct type, so the panel can
// decide whether to load it (idle) or offer it (another transcript is open).
export const interceptedTranscriptMessageSchema = z.object({
  type: z.literal("intercepted-transcript"),
  data: transcriptResponseSchema,
});

export const discoveryStartedMessageSchema = discoveryTargetSchema.extend({
  type: z.literal("discovery-started"),
});

export const discoveryAwaitingActionMessageSchema = discoveryTargetSchema.extend({
  type: z.literal("discovery-awaiting-action"),
});

export const discoveryResultMessageSchema = z.object({
  type: z.literal("discovery-result"),
  target: discoveryTargetSchema,
  data: transcriptResponseSchema,
  diagnostics: discoveryDiagnosticsSchema,
});

export const discoveryEmptyMessageSchema = z.object({
  type: z.literal("discovery-empty"),
  target: discoveryTargetSchema,
  diagnostics: discoveryDiagnosticsSchema,
  media: mediaPlaybackStateSchema.nullable(),
});

export const discoveryErrorMessageSchema = z.object({
  type: z.literal("discovery-error"),
  error: z.string(),
  target: discoveryTargetSchema.optional(),
});

export const playlistResultMessageSchema = z.object({
  type: z.literal("playlist-result"),
  data: playlistResponseSchema,
});

export const playlistErrorMessageSchema = z.object({
  type: z.literal("playlist-error"),
  error: z.string(),
});

export const channelResultMessageSchema = z.object({
  type: z.literal("channel-result"),
  data: channelResponseSchema,
});

export const channelErrorMessageSchema = z.object({
  type: z.literal("channel-error"),
  error: z.string(),
});

export const transcriptionProgressMessageSchema = z.object({
  type: z.literal("transcription-progress"),
  videoId: z.string(),
  progress: z.number(),
  segments: z.array(segmentSchema),
});

export const transcriptionCompleteMessageSchema = z.object({
  type: z.literal("transcription-complete"),
  videoId: z.string(),
  title: z.string(),
  segments: z.array(segmentSchema),
});

export const transcriptionErrorMessageSchema = z.object({
  type: z.literal("transcription-error"),
  error: z.string(),
  videoId: z.string().optional(),
});

export const transcriptionStartedMessageSchema = tabTranscriptionTargetSchema.extend({
  type: z.literal("transcription-started"),
});

export const transcriptionAwaitingActionMessageSchema = tabTranscriptionTargetSchema.extend({
  type: z.literal("transcription-awaiting-action"),
});

export type TranscriptResultMessage = z.infer<typeof transcriptResultMessageSchema>;
export type TranscriptErrorMessage = z.infer<typeof transcriptErrorMessageSchema>;
export type TranscriptReply = z.infer<typeof transcriptReplySchema>;
export type InterceptedTranscriptMessage = z.infer<typeof interceptedTranscriptMessageSchema>;
export type DiscoveryStartedMessage = z.infer<typeof discoveryStartedMessageSchema>;
export type DiscoveryAwaitingActionMessage = z.infer<typeof discoveryAwaitingActionMessageSchema>;
export type DiscoveryResultMessage = z.infer<typeof discoveryResultMessageSchema>;
export type DiscoveryEmptyMessage = z.infer<typeof discoveryEmptyMessageSchema>;
export type DiscoveryErrorMessage = z.infer<typeof discoveryErrorMessageSchema>;
export type PlaylistResultMessage = z.infer<typeof playlistResultMessageSchema>;
export type PlaylistErrorMessage = z.infer<typeof playlistErrorMessageSchema>;
export type ChannelResultMessage = z.infer<typeof channelResultMessageSchema>;
export type ChannelErrorMessage = z.infer<typeof channelErrorMessageSchema>;
export type TranscriptionProgressMessage = z.infer<typeof transcriptionProgressMessageSchema>;
export type TranscriptionCompleteMessage = z.infer<typeof transcriptionCompleteMessageSchema>;
export type TranscriptionErrorMessage = z.infer<typeof transcriptionErrorMessageSchema>;
export type TranscriptionStartedMessage = z.infer<typeof transcriptionStartedMessageSchema>;
export type TranscriptionAwaitingActionMessage = z.infer<typeof transcriptionAwaitingActionMessageSchema>;

// ---------- background -> content script ----------

export const scanTimedTextMessageSchema = z.object({
  type: z.literal("scan-timed-text"),
});

export type ScanTimedTextMessage = z.infer<typeof scanTimedTextMessageSchema>;

// ---------- background <-> offscreen document ----------

export const offscreenStartCaptureMessageSchema = z.object({
  type: z.literal("offscreen-start-capture"),
  streamId: z.string(),
  videoId: z.string(),
  title: z.string(),
});

export const offscreenStopCaptureMessageSchema = z.object({
  type: z.literal("offscreen-stop-capture"),
});

export const offscreenTranscribeFileMessageSchema = z.object({
  type: z.literal("offscreen-transcribe-file"),
  blobUrl: z.string(),
  videoId: z.string(),
  title: z.string(),
});

/** Everything the offscreen document acts on. */
export const offscreenMessageSchema = z.discriminatedUnion("type", [
  offscreenStartCaptureMessageSchema,
  offscreenStopCaptureMessageSchema,
  offscreenTranscribeFileMessageSchema,
  mediaPlaybackStateMessageSchema,
]);

export type OffscreenMessage = z.infer<typeof offscreenMessageSchema>;

// ---------- unions ----------

export const backgroundToPanelMessageSchema = z.discriminatedUnion("type", [
  transcriptResultMessageSchema,
  transcriptErrorMessageSchema,
  interceptedTranscriptMessageSchema,
  discoveryStartedMessageSchema,
  discoveryAwaitingActionMessageSchema,
  discoveryResultMessageSchema,
  discoveryEmptyMessageSchema,
  discoveryErrorMessageSchema,
  playlistResultMessageSchema,
  playlistErrorMessageSchema,
  channelResultMessageSchema,
  channelErrorMessageSchema,
  transcriptionProgressMessageSchema,
  transcriptionCompleteMessageSchema,
  transcriptionErrorMessageSchema,
  transcriptionStartedMessageSchema,
  transcriptionAwaitingActionMessageSchema,
  mediaPlaybackStateMessageSchema,
  playerTimeMessageSchema,
]);

/** Every message the background service worker acts on. */
export const extensionMessageSchema = z.discriminatedUnion("type", [
  // content script -> background
  playerTimeMessageSchema,
  timedTextPageSnapshotMessageSchema,
  timedTextResourceMessageSchema,
  mediaPlaybackStateMessageSchema,
  interceptedCaptureMessageSchema,
  // side panel -> background
  fetchTranscriptMessageSchema,
  fetchPlaylistMessageSchema,
  fetchChannelMessageSchema,
  seekToMessageSchema,
  discoverCurrentTabMessageSchema,
  rediscoverTabMessageSchema,
  prepareUrlDiscoveryMessageSchema,
  getDiscoveryStateMessageSchema,
  cancelPendingDiscoveryMessageSchema,
  selectDiscoveredTrackMessageSchema,
  startTranscriptionMessageSchema,
  getTabTranscriptionStateMessageSchema,
  cancelPendingTranscriptionMessageSchema,
  stopTranscriptionMessageSchema,
  transcribeFileMessageSchema,
  // offscreen document -> background
  transcriptionCompleteMessageSchema,
  transcriptionErrorMessageSchema,
]);

export type BackgroundToPanelMessage = z.infer<typeof backgroundToPanelMessageSchema>;
export type ExtensionMessage = z.infer<typeof extensionMessageSchema>;

export type ContentToBackgroundMessage =
  | PlayerTimeMessage
  | TimedTextPageSnapshotMessage
  | TimedTextResourceMessage
  | MediaPlaybackStateMessage
  | InterceptedCaptureMessage;

export type BackgroundToContentMessage = SeekToMessage | ScanTimedTextMessage;

// ---------- helpers ----------

/** Parse a message from chrome.runtime.onMessage; null when it is not for us. */
export function parseExtensionMessage(raw: unknown): ExtensionMessage | null {
  const result = extensionMessageSchema.safeParse(raw);
  return result.success ? result.data : null;
}

export function parseBackgroundMessage(raw: unknown): BackgroundToPanelMessage | null {
  const result = backgroundToPanelMessageSchema.safeParse(raw);
  return result.success ? result.data : null;
}

export function parseOffscreenMessage(raw: unknown): OffscreenMessage | null {
  const result = offscreenMessageSchema.safeParse(raw);
  return result.success ? result.data : null;
}

/** Parse a sendMessage reply; a malformed reply is reported like any other failure. */
export function parseReply<T>(schema: z.ZodType<T>, raw: unknown, what: string): T {
  const result = schema.safeParse(raw);
  if (!result.success) throw new Error(`The extension returned an unexpected ${what} reply.`);
  return result.data;
}
