const VIDEO_ID_RE = /^[a-zA-Z0-9_-]{11}$/;
const INNERTUBE_PLAYER_URL = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";
const USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";
function jsonResponse(data, status) {
    return new Response(JSON.stringify(data), {
        status,
        headers: {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*",
        },
    });
}
function errorResponse(error, message, status) {
    return jsonResponse({ error, message }, status);
}
function parseSegments(events) {
    const segments = [];
    for (const event of events) {
        if (!event.segs || event.segs.length === 0)
            continue;
        if (event.tStartMs === undefined)
            continue;
        const text = event.segs
            .map((seg) => seg.utf8 ?? "")
            .join("")
            .replace(/\n/g, " ")
            .trim();
        if (text.length === 0)
            continue;
        segments.push({
            start: event.tStartMs / 1000,
            duration: (event.dDurationMs ?? 0) / 1000,
            text,
        });
    }
    return segments;
}
function mapTracks(captionTracks) {
    return captionTracks.map((track) => ({
        languageCode: track.languageCode,
        name: track.name?.simpleText ?? track.languageCode,
        ...(track.kind ? { kind: track.kind } : {}),
    }));
}
export const onRequestPost = async ({ request }) => {
    let body;
    try {
        body = (await request.json());
    }
    catch {
        return errorResponse("invalid_request", "Request body must be valid JSON.", 400);
    }
    const videoId = typeof body.videoId === "string" ? body.videoId : "";
    const lang = typeof body.lang === "string" ? body.lang : undefined;
    const translateTo = typeof body.translateTo === "string" ? body.translateTo : undefined;
    if (!VIDEO_ID_RE.test(videoId)) {
        return errorResponse("invalid_id", "Invalid video ID. Expected an 11-character YouTube video ID.", 400);
    }
    // Step 1: Call Innertube player endpoint to get caption tracks
    let playerData;
    try {
        const playerResponse = await fetch(INNERTUBE_PLAYER_URL, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "User-Agent": USER_AGENT,
            },
            body: JSON.stringify({
                context: {
                    client: {
                        clientName: "WEB",
                        clientVersion: "2.20240101.00.00",
                    },
                },
                videoId,
            }),
        });
        if (playerResponse.status === 429) {
            return errorResponse("rate_limited", "YouTube is temporarily limiting requests. Try again in a moment.", 429);
        }
        if (!playerResponse.ok) {
            return errorResponse("fetch_failed", `YouTube returned status ${String(playerResponse.status)}.`, 502);
        }
        playerData = (await playerResponse.json());
    }
    catch {
        return errorResponse("fetch_failed", "Failed to connect to YouTube. Please try again.", 502);
    }
    // Extract video details
    const videoDetails = playerData.videoDetails;
    if (!videoDetails) {
        return errorResponse("unavailable", "This video is private, restricted, or does not exist.", 404);
    }
    const title = videoDetails.title ?? "Untitled";
    // Extract caption tracks
    const captions = playerData.captions;
    const captionTracks = captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!captionTracks || captionTracks.length === 0) {
        return errorResponse("no_captions", "This video does not have captions. Try a video where the creator has enabled captions.", 404);
    }
    // Find the requested track
    let selectedTrack;
    if (lang) {
        selectedTrack = captionTracks.find((t) => t.languageCode === lang);
    }
    if (!selectedTrack) {
        selectedTrack = captionTracks[0];
    }
    if (!selectedTrack) {
        return errorResponse("no_captions", "No caption tracks available.", 404);
    }
    const isAutoGenerated = selectedTrack.kind === "asr";
    // Step 2: Fetch the transcript text
    let transcriptUrl = `${selectedTrack.baseUrl}&fmt=json3`;
    if (translateTo) {
        transcriptUrl += `&tlang=${encodeURIComponent(translateTo)}`;
    }
    let transcriptData;
    try {
        const transcriptResponse = await fetch(transcriptUrl, {
            headers: { "User-Agent": USER_AGENT },
        });
        if (transcriptResponse.status === 429) {
            return errorResponse("rate_limited", "YouTube is temporarily limiting requests. Try again in a moment.", 429);
        }
        if (!transcriptResponse.ok) {
            return errorResponse("fetch_failed", `Failed to fetch transcript (status ${String(transcriptResponse.status)}).`, 502);
        }
        transcriptData = (await transcriptResponse.json());
    }
    catch {
        return errorResponse("fetch_failed", "Failed to fetch transcript data. Please try again.", 502);
    }
    const events = transcriptData.events ?? [];
    const segments = parseSegments(events);
    if (segments.length === 0) {
        return errorResponse("no_captions", "Transcript is empty. The video may have captions but no text content.", 404);
    }
    const response = {
        videoId,
        title,
        language: selectedTrack.name?.simpleText ?? selectedTrack.languageCode,
        isAutoGenerated,
        tracks: mapTracks(captionTracks),
        segments,
        ...(translateTo
            ? {
                translatedFrom: selectedTrack.languageCode,
                translatedTo: translateTo,
            }
            : {}),
    };
    return jsonResponse(response, 200);
};
// Handle CORS preflight
export const onRequestOptions = async () => {
    return new Response(null, {
        status: 204,
        headers: {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Methods": "POST, OPTIONS",
            "Access-Control-Allow-Headers": "Content-Type",
            "Access-Control-Max-Age": "86400",
        },
    });
};
