import {
    INNERTUBE_PLAYER_URL,
    PLAYER_CLIENTS,
    WEB_USER_AGENT,
} from "../_shared/innertube";

interface Env {
    // No bindings needed for basic Innertube proxy
}

interface TranscriptRequest {
    videoId?: unknown;
    lang?: unknown;
    translateTo?: unknown;
}

interface Segment {
    start: number;
    duration: number;
    text: string;
}

interface Track {
    languageCode: string;
    name: string;
    kind?: string;
}

interface Chapter {
    title: string;
    start: number;
}

interface TranscriptResponse {
    videoId: string;
    title: string;
    language: string;
    isAutoGenerated: boolean;
    tracks: Track[];
    segments: Segment[];
    chapters?: Chapter[];
    translatedFrom?: string;
    translatedTo?: string;
}

interface ApiError {
    error: string;
    message: string;
}

const VIDEO_ID_RE = /^[a-zA-Z0-9_-]{11}$/;

function jsonResponse(data: TranscriptResponse | ApiError, status: number): Response {
    return new Response(JSON.stringify(data), {
        status,
        headers: {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*",
        },
    });
}

function errorResponse(error: string, message: string, status: number): Response {
    return jsonResponse({error, message}, status);
}

interface InnertubeTrack {
    baseUrl: string;
    languageCode: string;
    kind?: string;
    name?: {simpleText?: string; runs?: Array<{text?: string}>};
}

interface InnertubeEvent {
    tStartMs?: number;
    dDurationMs?: number;
    segs?: Array<{utf8?: string}>;
}

/** Data extracted from a successful player response. */
interface PlayerResult {
    title: string;
    captionTracks: InnertubeTrack[];
    shortDescription: string;
    userAgent: string;
}

function parseSegments(events: InnertubeEvent[]): Segment[] {
    const segments: Segment[] = [];

    for (const event of events) {
        if (!event.segs || event.segs.length === 0) continue;
        if (event.tStartMs === undefined) continue;

        const text = event.segs
            .map((seg) => seg.utf8 ?? "")
            .join("")
            .replace(/\n/g, " ")
            .trim();

        if (text.length === 0) continue;

        segments.push({
            start: event.tStartMs / 1000,
            duration: (event.dDurationMs ?? 0) / 1000,
            text,
        });
    }

    return segments;
}

function getTrackName(track: InnertubeTrack): string {
    return track.name?.simpleText
        ?? track.name?.runs?.[0]?.text
        ?? track.languageCode;
}

function mapTracks(captionTracks: InnertubeTrack[]): Track[] {
    return captionTracks.map((track) => ({
        languageCode: track.languageCode,
        name: getTrackName(track),
        ...(track.kind ? {kind: track.kind} : {}),
    }));
}

function parseChaptersFromDescription(description: string): Chapter[] {
    if (!description) return [];
    const TIMESTAMP_RE = /^(?:(\d{1,2}):)?(\d{1,2}):(\d{2})\s+(.+)/;
    const chapters: Chapter[] = [];
    for (const line of description.split("\n")) {
        const match = TIMESTAMP_RE.exec(line.trim());
        if (!match) continue;
        const hours = match[1] ? parseInt(match[1], 10) : 0;
        const minutes = parseInt(match[2]!, 10);
        const seconds = parseInt(match[3]!, 10);
        const title = match[4]!.trim();
        if (title.length === 0) continue;
        chapters.push({title, start: hours * 3600 + minutes * 60 + seconds});
    }
    if (chapters.length < 3 || chapters[0]?.start !== 0) return [];
    return chapters;
}

/**
 * Extract videoDetails and captionTracks from a player response payload.
 * Returns undefined if the response is UNPLAYABLE or missing captions.
 */
function extractPlayerResult(
    playerData: Record<string, unknown>,
    userAgent: string,
): PlayerResult | undefined {
    const playabilityStatus = playerData.playabilityStatus as
        | {status?: string}
        | undefined;

    if (playabilityStatus?.status === "UNPLAYABLE") {
        return undefined;
    }

    const videoDetails = playerData.videoDetails as
        | {title?: string; videoId?: string; shortDescription?: string}
        | undefined;

    if (!videoDetails) {
        return undefined;
    }

    const captions = playerData.captions as
        | {playerCaptionsTracklistRenderer?: {captionTracks?: InnertubeTrack[]}}
        | undefined;

    const captionTracks =
        captions?.playerCaptionsTracklistRenderer?.captionTracks;

    if (!captionTracks || captionTracks.length === 0) {
        return undefined;
    }

    return {
        title: videoDetails.title ?? "Untitled",
        captionTracks,
        shortDescription: videoDetails.shortDescription ?? "",
        userAgent,
    };
}

/**
 * Try each Innertube client in order until one returns a playable response
 * with caption tracks. Returns the parsed player result, or an error response
 * if all clients fail.
 */
async function tryInnertubeClients(
    videoId: string,
): Promise<{result: PlayerResult} | {error: Response}> {
    let lastWasRateLimited = false;

    for (const client of PLAYER_CLIENTS) {
        let playerResponse: Response;
        try {
            playerResponse = await fetch(INNERTUBE_PLAYER_URL, {
                method: "POST",
                headers: client.headers,
                body: JSON.stringify({
                    context: client.context,
                    videoId,
                }),
            });
        } catch {
            // Network error — try next client
            continue;
        }

        if (playerResponse.status === 429) {
            lastWasRateLimited = true;
            continue;
        }

        if (!playerResponse.ok) {
            continue;
        }

        const playerData = (await playerResponse.json()) as Record<string, unknown>;
        const result = extractPlayerResult(playerData, client.userAgent);

        if (result) {
            return {result};
        }
        // UNPLAYABLE or missing captions — try next client
    }

    if (lastWasRateLimited) {
        return {
            error: errorResponse(
                "rate_limited",
                "YouTube is temporarily limiting requests. Try again in a moment.",
                429,
            ),
        };
    }

    return {
        error: errorResponse(
            "unavailable",
            "This video is private, restricted, or does not exist.",
            404,
        ),
    };
}

/**
 * Fallback: scrape the watch page HTML for ytInitialPlayerResponse.
 */
async function scrapeWatchPage(
    videoId: string,
): Promise<PlayerResult | undefined> {
    const watchUrl = `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`;

    let html: string;
    try {
        const response = await fetch(watchUrl, {
            headers: {"User-Agent": WEB_USER_AGENT},
        });

        if (!response.ok) {
            return undefined;
        }

        html = await response.text();
    } catch {
        return undefined;
    }

    const pattern = /var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\});/s;
    const match = pattern.exec(html);

    if (!match?.[1]) {
        return undefined;
    }

    let playerData: Record<string, unknown>;
    try {
        playerData = JSON.parse(match[1]) as Record<string, unknown>;
    } catch {
        return undefined;
    }

    return extractPlayerResult(playerData, WEB_USER_AGENT);
}

export const onRequestPost: PagesFunction<Env> = async ({request}) => {
    let body: TranscriptRequest;
    try {
        body = (await request.json()) as TranscriptRequest;
    } catch {
        return errorResponse("invalid_request", "Request body must be valid JSON.", 400);
    }

    const videoId = typeof body.videoId === "string" ? body.videoId : "";
    const lang = typeof body.lang === "string" ? body.lang : undefined;
    const translateTo = typeof body.translateTo === "string" ? body.translateTo : undefined;

    if (!VIDEO_ID_RE.test(videoId)) {
        return errorResponse(
            "invalid_id",
            "Invalid video ID. Expected an 11-character YouTube video ID.",
            400,
        );
    }

    // Step 1: Try Innertube clients in order
    const clientAttempt = await tryInnertubeClients(videoId);

    let playerResult: PlayerResult;

    if ("result" in clientAttempt) {
        playerResult = clientAttempt.result;
    } else {
        // Step 1b: All clients failed — try scraping the watch page
        const scraped = await scrapeWatchPage(videoId);

        if (!scraped) {
            return clientAttempt.error;
        }

        playerResult = scraped;
    }

    const {title, captionTracks, shortDescription} = playerResult;
    const chapters = parseChaptersFromDescription(shortDescription);

    // Find the requested track
    let selectedTrack: InnertubeTrack | undefined;

    if (lang) {
        selectedTrack = captionTracks.find((t) => t.languageCode === lang);
    }

    if (!selectedTrack) {
        selectedTrack = captionTracks[0];
    }

    if (!selectedTrack) {
        return errorResponse("no_captions", "No caption tracks available.", 404);
    }

    const isAutoGenerated = selectedTrack.kind === "asr";

    // Step 2: Fetch the transcript text
    // Strip any existing fmt param (ANDROID returns &fmt=srv3) before adding json3
    let transcriptUrl = selectedTrack.baseUrl.replace(/&fmt=[^&]*/, "") + "&fmt=json3";
    if (translateTo) {
        transcriptUrl += `&tlang=${encodeURIComponent(translateTo)}`;
    }

    let transcriptData: {events?: InnertubeEvent[]};
    try {
        const transcriptResponse = await fetch(transcriptUrl, {
            headers: {"User-Agent": playerResult.userAgent},
        });

        if (transcriptResponse.status === 429) {
            return errorResponse(
                "rate_limited",
                "YouTube is temporarily limiting requests. Try again in a moment.",
                429,
            );
        }

        if (!transcriptResponse.ok) {
            return errorResponse(
                "fetch_failed",
                `Failed to fetch transcript (status ${String(transcriptResponse.status)}).`,
                502,
            );
        }

        const rawText = await transcriptResponse.text();
        transcriptData = JSON.parse(rawText) as {events?: InnertubeEvent[]};
    } catch {
        return errorResponse(
            "fetch_failed",
            "Failed to fetch transcript data. Please try again.",
            502,
        );
    }

    const events = transcriptData.events ?? [];
    const segments = parseSegments(events);

    if (segments.length === 0) {
        return errorResponse(
            "no_captions",
            "Transcript is empty. The video may have captions but no text content.",
            404,
        );
    }

    const response: TranscriptResponse = {
        videoId,
        title,
        language: getTrackName(selectedTrack),
        isAutoGenerated,
        tracks: mapTracks(captionTracks),
        segments,
        ...(chapters.length > 0 ? {chapters} : {}),
        ...(translateTo
            ? {
                translatedFrom: selectedTrack.languageCode,
                translatedTo: translateTo,
            }
            : {}),
    };

    return jsonResponse(response, 200);
};

// Handle CORS preflight
export const onRequestOptions: PagesFunction<Env> = async () => {
    return new Response(null, {
        status: 204,
        headers: {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Methods": "POST, OPTIONS",
            "Access-Control-Allow-Headers": "Content-Type",
            "Access-Control-Max-Age": "86400",
        },
    });
};
