// Types that cross chrome.runtime messaging live in src/lib/messages/schema.ts
// and are re-exported here type-only; the rest are storage-local shapes.
export type {
  ApiError,
  Chapter,
  ChannelResponse,
  Platform,
  PlaylistResponse,
  Segment,
  Track,
  TranscriptResponse,
} from "../lib/messages/schema";
import type { Platform, Segment } from "../lib/messages/schema";

export interface ParagraphSegment {
  start: number;
  duration: number;
  text: string;
  originalSegments: Segment[];
}

export interface HistoryEntry {
  videoId: string;
  title: string;
  language: string;
  thumbnailUrl: string;
  fetchedAt: string;
  segmentCount: number;
  wordCount: number;
  platform?: Platform;
  pageUrl?: string;
}

export interface NoteEntry {
  segmentIndex: number;
  text: string;
  createdAt: string;
}

export interface SavedTranscript {
  videoId: string;
  title: string;
  language: string;
  isAutoGenerated: boolean;
  segments: Segment[];
  pageUrl?: string;
  savedAt: string;
  highlights: number[];
  notes: NoteEntry[];
  tags: string[];
}

export type AiFeature = "summary" | "bulletPoints" | "qaExtract";
