export interface Segment {
  start: number;
  duration: number;
  text: string;
}

export interface ParagraphSegment {
  start: number;
  duration: number;
  text: string;
  originalSegments: Segment[];
}

export interface Track {
  id?: string;
  languageCode: string;
  name: string;
  kind?: string;
  format?: string;
  source?: string;
}

export interface TranscriptResponse {
  videoId: string;
  title: string;
  language: string;
  isAutoGenerated: boolean;
  tracks: Track[];
  segments: Segment[];
  chapters?: Chapter[];
  translatedFrom?: string;
  translatedTo?: string;
  pageUrl?: string;
  source?: "page-track" | "network-resource" | "platform-adapter" | "on-device";
}

export interface ApiError {
  error: "no_captions" | "invalid_id" | "unavailable" | "rate_limited" | "fetch_failed" | "invalid_request" | "transcription_failed";
  message: string;
}

export interface Chapter {
  title: string;
  start: number;
}

export interface HistoryEntry {
  videoId: string;
  title: string;
  language: string;
  thumbnailUrl: string;
  fetchedAt: string;
  segmentCount: number;
  wordCount: number;
  platform?: Platform;
  pageUrl?: string;
}

export interface NoteEntry {
  segmentIndex: number;
  text: string;
  createdAt: string;
}

export interface SavedTranscript {
  videoId: string;
  title: string;
  language: string;
  isAutoGenerated: boolean;
  segments: Segment[];
  pageUrl?: string;
  savedAt: string;
  highlights: number[];
  notes: NoteEntry[];
  tags: string[];
}

export type Platform = "web" | "youtube";

export interface PlaylistResponse {
  playlistTitle: string;
  videos: { videoId: string; title: string; duration: string }[];
}

export interface ChannelResponse {
  channelTitle: string;
  videos: { videoId: string; title: string; duration: string }[];
}

export type AiFeature = "summary" | "bulletPoints" | "qaExtract";
