import {lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState} from "react";
import type {ApiError, Chapter, NoteEntry, Platform, Preferences, SavedTranscript, Segment, Track, TranscriptResponse} from "../types/transcript";
import {UrlInput} from "../components/UrlInput";
import {TranscriptView} from "../components/TranscriptView";
import {ExportBar} from "../components/ExportBar";
import {ErrorMessage} from "../components/ErrorMessage";
import {LoadingSpinner} from "../components/LoadingSpinner";
import {TagEditor} from "../components/TagEditor";
import {addToHistory} from "../lib/storage/history";
import {getSavedTranscript, saveTranscript, updateHighlights, updateNotes, updateTags} from "../lib/storage/saved";
import {BatchProcessor, type BatchState, type BatchItem} from "../lib/batch/queue";
import {BatchResultsNav} from "../components/BatchResultsNav";

// ---------- lazy imports ----------

const Settings = lazy(() => import("../components/Settings").then((m) => ({default: m.Settings})));
const AiPanel = lazy(() => import("../components/AiPanel").then((m) => ({default: m.AiPanel})));
const History = lazy(() => import("../components/History").then((m) => ({default: m.History})));
const SavedList = lazy(() => import("../components/SavedList").then((m) => ({default: m.SavedList})));
const BatchProgress = lazy(() => import("../components/BatchProgress").then((m) => ({default: m.BatchProgress})));
const LegalPage = lazy(() => import("../components/LegalPage").then((m) => ({default: m.LegalPage})));

// ---------- types ----------

type AppState = "idle" | "loading" | "loaded" | "error" | "no-captions" | "transcribing";
type Modal = "settings" | "history" | "saved" | null;

interface YTPlayer {
    seekTo: (seconds: number, allowSeekAhead: boolean) => void;
    getCurrentTime: () => number;
    getPlayerState: () => number;
}

interface TranscriptData {
    videoId: string;
    title: string;
    language: string;
    isAutoGenerated: boolean;
    tracks: Track[];
    segments: Segment[];
    chapters?: Chapter[];
}

// ---------- helpers ----------

const CAPTURE_VIA_TAB_TIMEOUT_MS = 20_000;
// How long to wait for the MAIN-world interceptor on the user's
// existing YouTube tab to deliver an `intercepted-transcript` for
// this videoId before falling back to opening a helper tab. Capture
// from the existing tab normally lands in 2–4 s.
const INTERCEPT_GRACE_MS = 6_000;

// Wait for an `intercepted-transcript` broadcast that matches this
// videoId without spawning any tabs. Used as a quiet pre-check
// before the captureViaYouTubeTab fallback so the common case (user
// already sits on the watch page, content.ts + correlator deliver on
// their own) doesn't open a duplicate helper tab.
function waitForInterceptedTranscript(videoId: string, timeoutMs: number): Promise<boolean> {
    return new Promise<boolean>((resolve) => {
        let resolved = false;
        const finish = (ok: boolean) => {
            if (resolved) return;
            resolved = true;
            chrome.runtime.onMessage.removeListener(listener);
            resolve(ok);
        };
        const listener = (message: { type?: string; data?: { videoId?: string } }) => {
            if (message?.type === "intercepted-transcript" && message.data?.videoId === videoId) {
                finish(true);
            }
        };
        chrome.runtime.onMessage.addListener(listener);
        setTimeout(() => finish(false), timeoutMs);
    });
}

// Paste-URL recovery: when the SW's Innertube fallback fails for a
// video the user is not currently watching, open the watch page in a
// background tab and wait for the MAIN-world interceptor + correlator
// to broadcast a transcript for this videoId. YouTube's own page JS
// makes the authenticated /youtubei/v1/player call we cannot replicate
// from MV3, the interceptor rides it, and the SW emits
// `intercepted-transcript` once segments are resolved. The 20 s ceiling
// is generous — a normal capture lands in 2–6 s.
async function captureViaYouTubeTab(videoId: string): Promise<boolean> {
    let createdTabId: number | null = null;
    return new Promise<boolean>((resolve) => {
        let resolved = false;
        const finish = (ok: boolean) => {
            if (resolved) return;
            resolved = true;
            chrome.runtime.onMessage.removeListener(listener);
            // Close the helper tab whether we captured or timed out — it
            // was only opened to wake the MAIN-world interceptor; the
            // user is on the side panel, not watching the video here.
            if (createdTabId !== null) {
                chrome.tabs.remove(createdTabId).catch(() => {});
            }
            resolve(ok);
        };
        const listener = (message: { type?: string; data?: { videoId?: string } }) => {
            if (message?.type === "intercepted-transcript" && message.data?.videoId === videoId) {
                finish(true);
            }
        };
        chrome.runtime.onMessage.addListener(listener);
        chrome.tabs
            .create({url: `https://www.youtube.com/watch?v=${videoId}`, active: false})
            .then((tab) => {
                if (typeof tab.id === "number") createdTabId = tab.id;
            })
            .catch(() => finish(false));
        setTimeout(() => finish(false), CAPTURE_VIA_TAB_TIMEOUT_MS);
    });
}

// ---------- header icons ----------

function GearIcon() {
    return (
        <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round"
                  d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7 7 0 010 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a7 7 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a7 7 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.991a7 7 0 010-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28z"/>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
        </svg>
    );
}

function ClockIcon() {
    return (
        <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
    );
}

function BookmarkIcon({filled}: { filled: boolean }) {
    return filled ? (
        <svg className="h-5 w-5" viewBox="0 0 24 24" fill="currentColor">
            <path fillRule="evenodd"
                  d="M6.32 2.577a49.255 49.255 0 0111.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 01-1.085.67L12 18.089l-7.165 3.583A.75.75 0 013.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93z"
                  clipRule="evenodd"/>
        </svg>
    ) : (
        <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round"
                  d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z"/>
        </svg>
    );
}

function FolderIcon() {
    return (
        <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round"
                  d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z"/>
        </svg>
    );
}

// ---------- main app ----------

export function App() {
    const [state, setState] = useState<AppState>("idle");
    const [transcript, setTranscript] = useState<TranscriptData | null>(null);
    const [error, setError] = useState<ApiError | null>(null);
    const [selectedRange, setSelectedRange] = useState<[number, number] | null>(null);
    const [cleanFillers, setCleanFillers] = useState(false);
    const [filterProfanity, setFilterProfanity] = useState(false);
    const [modal, setModal] = useState<Modal>(null);
    const [prefsVersion, setPrefsVersion] = useState(0);
    const [isSaved, setIsSaved] = useState(false);
    const [tags, setTags] = useState<string[]>([]);
    const [selectedLang, setSelectedLang] = useState<string | null>(null);
    const [highlights, setHighlights] = useState<number[]>([]);
    const [notes, setNotes] = useState<NoteEntry[]>([]);
    const [batchState, setBatchState] = useState<BatchState | null>(null);
    const [batchViewMode, setBatchViewMode] = useState<"progress" | "result">("progress");
    const [route, setRoute] = useState<string>(window.location.hash);
    const [currentTime, setCurrentTime] = useState(0);
    const [activePlatform, setActivePlatform] = useState<Platform>("youtube");
    const [transcriptionProgress, setTranscriptionProgress] = useState(0);
    const [pendingVideoId, setPendingVideoId] = useState<string | null>(null);
    const [pendingTitle, setPendingTitle] = useState("");
    const [liveCaptureVideoId, setLiveCaptureVideoId] = useState<string | null>(null);
    const lastFetchRef = useRef(0);
    const batchRef = useRef<BatchProcessor | null>(null);
    const lastPlayerTimeRef = useRef(0);
    // Tracks the live capture promise per videoId. The background tab
    // we spawn fires its own `video-info` which would re-enter
    // `fetchTranscript` and start an infinite tab cascade for videos the
    // SW Innertube path can't resolve. Holding the promise here lets the
    // listener bail (has() check) AND lets overlapping fetchTranscript
    // calls for the same videoId share a single capture instead of each
    // spawning their own helper tab.
    const captureInFlightRef = useRef<Map<string, Promise<boolean>>>(new Map());

    // Shim YTPlayer interface using message-based currentTime
    const playerRef = useRef<YTPlayer | null>(null);
    useEffect(() => {
        playerRef.current = {
            seekTo: (seconds: number) => {
                chrome.runtime.sendMessage({type: "seek-to", time: seconds}).catch(() => {});
            },
            getCurrentTime: () => currentTime,
            // Content script sends player-time every ~1s while playing.
            // If >1.5s since last message, video is likely paused.
            getPlayerState: () => (Date.now() - lastPlayerTimeRef.current < 1500 ? 1 : 2),
        };
    }, [currentTime]);

    // Listen for video-info messages from content script (via background).
    // When the MAIN-world interceptor has already populated us for this
    // videoId, skip the legacy 3-layer fetch — it would race and potentially
    // overwrite the live-captured data.
    useEffect(() => {
        const listener = (message: { type: string; videoId?: string; platform?: Platform }) => {
            if (message.type === "video-info" && message.videoId) {
                const platform = message.platform ?? "youtube";
                setActivePlatform(platform);
                if (liveCaptureVideoId === message.videoId) return;
                if (transcript?.videoId === message.videoId) return;
                // Suppress auto-fetch while paste-URL recovery is running for
                // this videoId — the background tab we just spawned will emit
                // its own `video-info` and we don't want to recursively retry.
                if (captureInFlightRef.current.has(message.videoId)) return;
                void fetchTranscript(message.videoId, platform);
            }
        };
        chrome.runtime.onMessage.addListener(listener);
        return () => chrome.runtime.onMessage.removeListener(listener);
    }, [liveCaptureVideoId, transcript?.videoId]);

    // Listen for intercepted-transcript broadcasts from the SW correlator.
    // These come for free whenever the user is on a YouTube watch page —
    // no button press required. Only auto-load when idle/loading/error,
    // never overwrite a paste-URL flow that's already produced a result.
    useEffect(() => {
        const listener = (message: { type: string; data?: TranscriptData }) => {
            if (message.type !== "intercepted-transcript" || !message.data) return;
            const incoming = message.data;
            if (transcript?.videoId === incoming.videoId && state === "loaded") return;
            setTranscript(incoming);
            setState("loaded");
            setError(null);
            setLiveCaptureVideoId(incoming.videoId);
            const wordCount = incoming.segments.reduce(
                (sum, s) => sum + s.text.split(/\s+/).filter((w) => w.length > 0).length,
                0,
            );
            void addToHistory({
                videoId: incoming.videoId,
                title: incoming.title,
                language: incoming.language,
                thumbnailUrl: `https://img.youtube.com/vi/${incoming.videoId}/mqdefault.jpg`,
                fetchedAt: new Date().toISOString(),
                segmentCount: incoming.segments.length,
                wordCount,
                platform: "youtube",
            });
        };
        chrome.runtime.onMessage.addListener(listener);
        return () => chrome.runtime.onMessage.removeListener(listener);
    }, [transcript?.videoId, state]);

    // Listen for player-time and transcription messages
    useEffect(() => {
        const listener = (message: { type: string; currentTime?: number; progress?: number; segments?: Segment[]; videoId?: string; title?: string; error?: string }) => {
            switch (message.type) {
                case "player-time":
                    if (message.currentTime !== undefined) {
                        lastPlayerTimeRef.current = Date.now();
                        setCurrentTime(message.currentTime);
                    }
                    break;
                case "transcription-progress":
                    setTranscriptionProgress(message.progress ?? 0);
                    if (message.segments && message.segments.length > 0) {
                        setTranscript((prev) => prev ? {...prev, segments: message.segments!} : {
                            videoId: message.videoId ?? "",
                            title: pendingTitle,
                            language: "en",
                            isAutoGenerated: true,
                            tracks: [],
                            segments: message.segments!,
                        });
                    }
                    break;
                case "transcription-complete":
                    if (message.segments) {
                        setTranscript({
                            videoId: message.videoId ?? pendingVideoId ?? "",
                            title: message.title ?? pendingTitle,
                            language: "en",
                            isAutoGenerated: true,
                            tracks: [],
                            segments: message.segments,
                        });
                        setState("loaded");
                        setTranscriptionProgress(0);
                    }
                    break;
                case "transcription-error":
                    setError({error: "fetch_failed", message: message.error ?? "Transcription failed"});
                    setState("error");
                    setTranscriptionProgress(0);
                    break;
            }
        };
        chrome.runtime.onMessage.addListener(listener);
        return () => chrome.runtime.onMessage.removeListener(listener);
    }, [pendingVideoId, pendingTitle]);

    // Hash-based routing
    useEffect(() => {
        const handler = () => setRoute(window.location.hash);
        window.addEventListener("hashchange", handler);
        return () => window.removeEventListener("hashchange", handler);
    }, []);

    // Load saved data (highlights, notes, tags) when transcript changes
    useEffect(() => {
        if (transcript) {
            getSavedTranscript(transcript.videoId).then((saved) => {
                setIsSaved(!!saved);
                setTags(saved?.tags ?? []);
                setHighlights(saved?.highlights ?? []);
                setNotes(saved?.notes ?? []);
            });
        } else {
            setIsSaved(false);
            setTags([]);
            setHighlights([]);
            setNotes([]);
        }
    }, [transcript?.videoId]);

    // Fetch transcript via extension message passing
    const fetchTranscript = useCallback(async (videoId: string, platform: Platform = "youtube", lang?: string, translateTo?: string) => {
        const now = Date.now();
        const elapsed = now - lastFetchRef.current;
        if (elapsed < 2000) {
            await new Promise((r) => setTimeout(r, 2000 - elapsed));
        }
        lastFetchRef.current = Date.now();

        setState("loading");
        setError(null);
        setSelectedRange(null);
        setActivePlatform(platform);
        // Stash the videoId for the whole attempt so error-state recovery
        // (Open on YouTube, Transcribe locally) has something to act on.
        setPendingVideoId(videoId);

        try {
            const response = await chrome.runtime.sendMessage({
                type: "fetch-transcript",
                videoId,
                platform,
                ...(lang ? {lang} : {}),
                ...(translateTo ? {translateTo} : {}),
            }) as { type: string; data?: TranscriptData; error?: ApiError };

            if (response.type === "transcript-error" && response.error) {
                // YouTube's anonymous Innertube clients (WEB_EMBEDDED_PLAYER,
                // TVHTML5_SIMPLY_EMBEDDED_PLAYER, ANDROID_VR + watch-page
                // scrape) drop captions for a non-trivial fraction of public
                // videos because the captionTrack URLs are gated by PO
                // tokens we cannot mint from MV3. The MAIN-world interceptor
                // (src/content/yt-interceptor.ts) rides on YouTube's own
                // authenticated /youtubei/v1/player + /get_transcript calls
                // — opening the watch page in a background tab lets the
                // correlator deliver the captions for any video YouTube's
                // own page can render them for. This replaces the previous
                // auto-cascade into `start-transcription` (chrome.tabCapture
                // against the active tab), which surfaced the misleading
                // "activeTab permission … Chrome pages cannot be captured."
                // error whenever the foreground tab was not the target.
                // Whisper is still reachable behind the explicit
                // "Transcribe locally" button on the error UI.
                if (platform === "youtube" &&
                    (response.error.error === "no_captions" ||
                        response.error.error === "fetch_failed")) {
                    // The user almost always already has the watch page open
                    // in some tab — the MAIN-world interceptor there fires
                    // `intercepted-transcript` for free in 2–4 s. Wait a
                    // bounded window for that broadcast BEFORE deciding to
                    // open a helper tab; without this, every side-panel
                    // open on a video the SW Innertube path can't resolve
                    // spawned a duplicate YouTube tab that flashed on
                    // screen for a few seconds before closing itself again.
                    if (await waitForInterceptedTranscript(videoId, INTERCEPT_GRACE_MS)) {
                        return;
                    }
                    // De-duplicate concurrent recoveries for the same
                    // videoId: cache the in-flight promise, share it with
                    // any overlapping fetchTranscript, and clear the slot
                    // only when this single capture settles. Two paste-X
                    // submits in quick succession now wait on the same
                    // helper tab instead of spawning two.
                    const map = captureInFlightRef.current;
                    let captureP = map.get(videoId);
                    if (!captureP) {
                        captureP = captureViaYouTubeTab(videoId).finally(() => {
                            // Only delete if our promise is still the one
                            // cached — defensive against the rare case of
                            // a parallel write replacing it.
                            if (map.get(videoId) === captureP) map.delete(videoId);
                        });
                        map.set(videoId, captureP);
                    }
                    const captured = await captureP;
                    if (captured) {
                        // The shared `intercepted-transcript` listener above
                        // has already set state="loaded" and populated the
                        // transcript; nothing more to do here.
                        return;
                    }
                }
                setError(response.error);
                setState("error");
                return;
            }

            if (response.type === "transcript-result" && response.data) {
                const td = response.data;
                setTranscript(td);
                setState("loaded");

                const wordCount = td.segments.reduce(
                    (sum, s) => sum + s.text.split(/\s+/).filter((w) => w.length > 0).length,
                    0,
                );
                const thumbnailUrl = platform === "vimeo"
                    ? `https://vumbnail.com/${videoId}.jpg`
                    : `https://img.youtube.com/vi/${videoId}/mqdefault.jpg`;
                void addToHistory({
                    videoId: td.videoId,
                    title: td.title,
                    language: td.language,
                    thumbnailUrl,
                    fetchedAt: new Date().toISOString(),
                    segmentCount: td.segments.length,
                    wordCount,
                    platform,
                });
            }
        } catch {
            setError({error: "fetch_failed", message: "Failed to fetch transcript. Please try again."});
            setState("error");
        }
    }, []);

    const handleSeek = useCallback((seconds: number) => {
        chrome.runtime.sendMessage({type: "seek-to", time: seconds}).catch(() => {});
    }, []);

    const handleSave = useCallback(async () => {
        if (!transcript) return;
        await saveTranscript({
            videoId: transcript.videoId,
            title: transcript.title,
            language: transcript.language,
            isAutoGenerated: transcript.isAutoGenerated,
            segments: transcript.segments,
            savedAt: new Date().toISOString(),
            highlights: [],
            notes: [],
            tags: [],
        });
        setIsSaved(true);
    }, [transcript]);

    const handleLoadSaved = useCallback((saved: SavedTranscript) => {
        setTranscript({
            videoId: saved.videoId,
            title: saved.title,
            language: saved.language,
            isAutoGenerated: saved.isAutoGenerated,
            tracks: [],
            segments: saved.segments,
        });
        setState("loaded");
        setIsSaved(true);
    }, []);

    const handlePreferencesChange = useCallback((_prefs: Preferences) => {
        setPrefsVersion((v) => v + 1);
    }, []);

    const handleRetry = useCallback(() => {
        setState("idle");
        setError(null);
    }, []);

    const handleStartTranscription = useCallback(() => {
        if (!pendingVideoId) return;
        setState("transcribing");
        setTranscriptionProgress(0);
        setTranscript(null);
        chrome.runtime.sendMessage({
            type: "start-transcription",
            videoId: pendingVideoId,
            title: pendingTitle,
        });
    }, [pendingVideoId, pendingTitle]);

    const handleStopTranscription = useCallback(() => {
        chrome.runtime.sendMessage({type: "stop-transcription"});
        setState("idle");
        setTranscriptionProgress(0);
    }, []);

    const handleLanguageChange = useCallback((langCode: string) => {
        if (!transcript) return;
        setSelectedLang(langCode);
        void fetchTranscript(transcript.videoId, activePlatform, langCode);
    }, [transcript, fetchTranscript, activePlatform]);

    const handleTagsChange = useCallback((newTags: string[]) => {
        if (!transcript) return;
        setTags(newTags);
        void updateTags(transcript.videoId, newTags);
    }, [transcript]);

    const handleHighlightToggle = useCallback((segmentIndex: number) => {
        if (!transcript || !isSaved) return;
        setHighlights(prev => {
            const next = prev.includes(segmentIndex)
                ? prev.filter(i => i !== segmentIndex)
                : [...prev, segmentIndex];
            void updateHighlights(transcript.videoId, next);
            return next;
        });
    }, [transcript, isSaved]);

    const handleNoteUpdate = useCallback((segmentIndex: number, text: string) => {
        if (!transcript || !isSaved) return;
        setNotes(prev => {
            const filtered = prev.filter(n => n.segmentIndex !== segmentIndex);
            const next = text.trim()
                ? [...filtered, {segmentIndex, text: text.trim(), createdAt: new Date().toISOString()}]
                : filtered;
            void updateNotes(transcript.videoId, next);
            return next;
        });
    }, [transcript, isSaved]);

    // ---------- batch handlers ----------

    const handleSubmitBatch = useCallback((videoIds: string[]) => {
        const processor = new BatchProcessor();
        batchRef.current = processor;
        processor.onProgress = (s) => setBatchState(s);
        processor.start(videoIds);
        setBatchViewMode("progress");
    }, []);

    const handleBatchViewResult = useCallback((videoId: string) => {
        const item = batchState?.items.find(i => i.videoId === videoId);
        if (item?.result) {
            setTranscript({
                videoId: item.result.videoId,
                title: item.result.title,
                language: item.result.language,
                isAutoGenerated: item.result.isAutoGenerated,
                tracks: item.result.tracks,
                segments: item.result.segments,
            });
            setState("loaded");
            setBatchViewMode("result");
        }
    }, [batchState]);

    const handleBackToBatch = useCallback(() => {
        setBatchViewMode("progress");
        setState("idle");
        setTranscript(null);
    }, []);

    const handleBatchCancel = useCallback(() => {
        batchRef.current?.cancel();
    }, []);

    const handleBatchRetry = useCallback(() => {
        batchRef.current?.retryFailed();
    }, []);

    const handleBatchExport = useCallback((format: string, mode: "separate" | "merged") => {
        if (!batchState || !batchRef.current) return;
        if (mode === "merged") batchRef.current.exportMerged(batchState.items, format);
        else batchRef.current.exportAsZip(batchState.items, format);
    }, [batchState]);

    const batchCompletedItems = useMemo(() => {
        if (!batchState) return [];
        return batchState.items
            .filter((i): i is BatchItem & {result: TranscriptResponse} => i.status === "success" && !!i.result)
            .map(i => ({videoId: i.videoId, title: i.title ?? i.videoId}));
    }, [batchState]);

    const iconBtnClass = "rounded-md p-1 text-slate-500 hover:bg-slate-200/40 hover:text-slate-200 dark:text-slate-500 dark:hover:bg-slate-800 dark:hover:text-slate-100 transition-colors";

    // ---------- legal page route ----------
    if (route === "#/legal") {
        return (
            <div className="min-h-screen bg-white dark:bg-slate-900">
                <header
                    className="border-b border-slate-200 bg-white/80 backdrop-blur-sm dark:border-slate-700 dark:bg-slate-900/80">
                    <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-2">
                        <span className="text-sm font-medium text-slate-900 dark:text-white">Transcript</span>
                    </div>
                </header>
                <Suspense fallback={null}>
                    <LegalPage onBack={() => {
                        window.location.hash = "";
                        setRoute("");
                    }}/>
                </Suspense>
            </div>
        );
    }

    // ---------- main app route ----------
    return (
        <div className="min-h-screen bg-white text-slate-900 dark:bg-[#0b0d10] dark:text-slate-100">
            {/* Header — single row, mostly negative space */}
            <header className="sticky top-0 z-20 border-b border-slate-200/70 bg-white/85 backdrop-blur-md dark:border-slate-800/60 dark:bg-[#0b0d10]/85">
                <div className="mx-auto flex max-w-5xl items-center gap-2 px-3 py-1.5">
                    {/* Word-mark — the wordmark IS the only branding here */}
                    <span className="font-serif text-[15px] italic leading-none tracking-tight text-slate-900 dark:text-slate-100">yt·tx</span>
                    {liveCaptureVideoId && transcript?.videoId === liveCaptureVideoId && state === "loaded" && (
                        <span
                            title="Captured live from the YouTube tab — no API call made"
                            className="inline-flex items-center gap-1 rounded-full border border-amber-400/30 bg-amber-400/10 px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-[0.08em] text-amber-700 dark:border-amber-300/20 dark:text-amber-300"
                        >
                            <span className="h-1 w-1 rounded-full bg-amber-500 dark:bg-amber-400" />
                            Live
                        </span>
                    )}
                    <div className="ml-auto flex items-center gap-0.5">
                        {state === "loaded" && (
                            <button
                                onClick={handleSave}
                                title={isSaved ? "Saved" : "Save transcript"}
                                className={iconBtnClass}
                                disabled={isSaved}
                            >
                                <BookmarkIcon filled={isSaved}/>
                            </button>
                        )}
                        <button onClick={() => setModal("history")} title="History" className={iconBtnClass}>
                            <ClockIcon/>
                        </button>
                        <button onClick={() => setModal("saved")} title="Saved transcripts" className={iconBtnClass}>
                            <FolderIcon/>
                        </button>
                        <button onClick={() => setModal("settings")} title="Settings" className={iconBtnClass}>
                            <GearIcon/>
                        </button>
                    </div>
                </div>
            </header>

            {/* Main content */}
            <div className="mx-auto max-w-5xl px-3 pt-3 pb-6">
                <UrlInput
                    onSubmit={(id, platform) => void fetchTranscript(id, platform)}
                    onSubmitBatch={handleSubmitBatch}
                    isLoading={state === "loading"}
                    compact={state !== "idle"}
                />

                {batchState && batchViewMode === "result" && batchCompletedItems.length > 0 && (
                    <BatchResultsNav
                        items={batchCompletedItems}
                        activeVideoId={transcript?.videoId ?? null}
                        onSelect={handleBatchViewResult}
                        onBackToBatch={handleBackToBatch}
                    />
                )}

                {batchState && batchViewMode === "progress" && (
                    <Suspense fallback={<div className="h-32 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>}>
                        <BatchProgress
                            batchState={batchState}
                            onRetry={handleBatchRetry}
                            onCancel={handleBatchCancel}
                            onViewResult={handleBatchViewResult}
                            onExport={handleBatchExport}
                        />
                    </Suspense>
                )}

                {state === "loading" && <LoadingSpinner/>}

                {state === "no-captions" && (
                    <div className="mt-8 text-center">
                        <h3 className="mb-1 text-base font-medium text-slate-900 dark:text-white">No transcript</h3>
                        <p className="mb-4 text-sm text-slate-500 dark:text-slate-400">
                            This video doesn't have subtitles. We can transcribe the audio locally — runs in your browser, ~2–3× realtime.
                        </p>
                        <button
                            onClick={handleStartTranscription}
                            className="rounded-md bg-slate-900 px-4 py-1.5 text-sm font-medium text-white hover:bg-slate-800 dark:bg-white dark:text-slate-900 dark:hover:bg-slate-200"
                        >
                            Transcribe
                        </button>
                    </div>
                )}

                {state === "transcribing" && (
                    <div className="mt-8 rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-700 dark:bg-slate-800">
                        <div className="mb-3 flex items-center justify-between">
                            <span className="text-sm font-semibold text-slate-900 dark:text-white">
                                Transcribing... {transcriptionProgress}%
                            </span>
                            <button
                                onClick={handleStopTranscription}
                                className="rounded-lg border border-slate-200 px-3 py-1 text-xs text-slate-600 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-400 dark:hover:bg-slate-700"
                            >
                                Stop
                            </button>
                        </div>
                        <div className="mb-4 h-2 w-full overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700">
                            <div
                                className="h-full rounded-full bg-blue-500 transition-all"
                                style={{width: `${Math.max(transcriptionProgress, 2)}%`}}
                            />
                        </div>
                        {transcript && transcript.segments.length > 0 && (
                            <TranscriptView
                                key={prefsVersion}
                                segments={transcript.segments}
                                title={transcript.title}
                                language={transcript.language}
                                isAutoGenerated={transcript.isAutoGenerated}
                                playerRef={playerRef}
                                selectedRange={selectedRange}
                                onSelectedRangeChange={setSelectedRange}
                                cleanFillers={cleanFillers}
                                onCleanFillersChange={setCleanFillers}
                                filterProfanity={filterProfanity}
                                onFilterProfanityChange={setFilterProfanity}
                            />
                        )}
                    </div>
                )}

                {state === "error" && error && (() => {
                    const failedVideoId = transcript?.videoId ?? pendingVideoId;
                    const canRecover = error.error === "fetch_failed" && !!failedVideoId;
                    const watchUrl = canRecover
                        ? activePlatform === "vimeo"
                            ? `https://vimeo.com/${failedVideoId}`
                            : `https://www.youtube.com/watch?v=${failedVideoId}`
                        : null;
                    return (
                        <ErrorMessage
                            error={error.error}
                            message={error.message}
                            onRetry={handleRetry}
                            onOpenOriginal={watchUrl ? () => {
                                chrome.tabs.create({url: watchUrl});
                            } : undefined}
                            onTranscribeLocal={canRecover ? () => {
                                if (!failedVideoId) return;
                                setPendingVideoId(failedVideoId);
                                setPendingTitle(transcript?.title ?? pendingTitle);
                                handleStartTranscription();
                            } : undefined}
                        />
                    );
                })()}

                {state === "loaded" && transcript && (
                    <div className="space-y-4">
                        {/* Tags */}
                        {isSaved && (
                            <div className="max-w-md">
                                <TagEditor tags={tags} onTagsChange={handleTagsChange} />
                            </div>
                        )}

                        {/* Language selector */}
                        {transcript.tracks.length > 1 && (
                            <div className="max-w-xs">
                                <label className="block text-xs font-medium text-slate-600 dark:text-slate-400 mb-1">
                                    Language
                                </label>
                                <select
                                    value={selectedLang ?? transcript.language}
                                    onChange={(e) => handleLanguageChange(e.target.value)}
                                    className="w-full rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200"
                                >
                                    {transcript.tracks.map((track) => (
                                        <option key={track.languageCode} value={track.languageCode}>
                                            {track.name} {track.kind === "asr" ? "(auto)" : ""}
                                        </option>
                                    ))}
                                </select>
                            </div>
                        )}

                        {/* Transcript */}
                        <TranscriptView
                            key={prefsVersion}
                            segments={transcript.segments}
                            title={transcript.title}
                            language={transcript.language}
                            isAutoGenerated={transcript.isAutoGenerated}
                            playerRef={playerRef}
                            selectedRange={selectedRange}
                            onSelectedRangeChange={setSelectedRange}
                            cleanFillers={cleanFillers}
                            onCleanFillersChange={setCleanFillers}
                            filterProfanity={filterProfanity}
                            onFilterProfanityChange={setFilterProfanity}
                            chapters={transcript.chapters}
                            highlights={highlights}
                            notes={notes}
                            onHighlightToggle={isSaved ? handleHighlightToggle : undefined}
                            onNoteUpdate={isSaved ? handleNoteUpdate : undefined}
                        />

                        {/* Export bar */}
                        <ExportBar
                            segments={transcript.segments}
                            title={transcript.title}
                            language={transcript.language}
                            videoId={transcript.videoId}
                            isAutoGenerated={transcript.isAutoGenerated}
                            showTimestamps={true}
                            selectedRange={selectedRange}
                            cleanFillers={cleanFillers}
                            chapters={transcript.chapters}
                            highlights={highlights}
                        />

                        {/* AI Panel */}
                        <Suspense
                            fallback={<div className="h-32 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>}>
                            <AiPanel transcript={transcript as TranscriptResponse} onSeek={handleSeek}/>
                        </Suspense>
                    </div>
                )}
            </div>

            {/* Modals */}
            <Suspense fallback={null}>
                <Settings
                    isOpen={modal === "settings"}
                    onClose={() => setModal(null)}
                    onPreferencesChange={handlePreferencesChange}
                />
                <History
                    isOpen={modal === "history"}
                    onClose={() => setModal(null)}
                    onSelectVideo={(videoId) => {
                        setModal(null);
                        // History entries with numeric-only IDs are Vimeo
                        const platform: Platform = /^\d+$/.test(videoId) ? "vimeo" : "youtube";
                        void fetchTranscript(videoId, platform);
                    }}
                />
                <SavedList
                    isOpen={modal === "saved"}
                    onClose={() => setModal(null)}
                    onLoadSaved={handleLoadSaved}
                />
            </Suspense>

            {/* Footer */}
            <footer className="mt-8 border-t border-slate-200 dark:border-slate-700">
                <div className="mx-auto max-w-5xl px-4 py-4 text-center text-xs text-slate-500 dark:text-slate-400">
                    <a href="#/legal" className="hover:text-slate-700 dark:hover:text-slate-300 underline">
                        Legal & Privacy
                    </a>
                </div>
            </footer>
        </div>
    );
}
