import {lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState} from "react";
import type {ApiError, Chapter, NoteEntry, Preferences, SavedTranscript, Segment, Track, TranscriptResponse} from "../types/transcript";
import {UrlInput} from "../components/UrlInput";
import {TranscriptView} from "../components/TranscriptView";
import {ExportBar} from "../components/ExportBar";
import {ErrorMessage} from "../components/ErrorMessage";
import {LoadingSpinner} from "../components/LoadingSpinner";
import {TagEditor} from "../components/TagEditor";
import {addToHistory} from "../lib/storage/history";
import {getSavedTranscript, saveTranscript, updateHighlights, updateNotes, updateTags} from "../lib/storage/saved";
import {BatchProcessor, type BatchState, type BatchItem} from "../lib/batch/queue";
import {BatchResultsNav} from "../components/BatchResultsNav";

// ---------- lazy imports ----------

const Settings = lazy(() => import("../components/Settings").then((m) => ({default: m.Settings})));
const AiPanel = lazy(() => import("../components/AiPanel").then((m) => ({default: m.AiPanel})));
const History = lazy(() => import("../components/History").then((m) => ({default: m.History})));
const SavedList = lazy(() => import("../components/SavedList").then((m) => ({default: m.SavedList})));
const BatchProgress = lazy(() => import("../components/BatchProgress").then((m) => ({default: m.BatchProgress})));
const LegalPage = lazy(() => import("../components/LegalPage").then((m) => ({default: m.LegalPage})));

// ---------- types ----------

type AppState = "idle" | "loading" | "loaded" | "error";
type Modal = "settings" | "history" | "saved" | null;

interface YTPlayer {
    seekTo: (seconds: number, allowSeekAhead: boolean) => void;
    getCurrentTime: () => number;
    getPlayerState: () => number;
}

interface TranscriptData {
    videoId: string;
    title: string;
    language: string;
    isAutoGenerated: boolean;
    tracks: Track[];
    segments: Segment[];
    chapters?: Chapter[];
}

// ---------- header icons ----------

function GearIcon() {
    return (
        <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round"
                  d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7 7 0 010 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a7 7 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a7 7 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.991a7 7 0 010-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28z"/>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
        </svg>
    );
}

function ClockIcon() {
    return (
        <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
    );
}

function BookmarkIcon({filled}: { filled: boolean }) {
    return filled ? (
        <svg className="h-5 w-5" viewBox="0 0 24 24" fill="currentColor">
            <path fillRule="evenodd"
                  d="M6.32 2.577a49.255 49.255 0 0111.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 01-1.085.67L12 18.089l-7.165 3.583A.75.75 0 013.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93z"
                  clipRule="evenodd"/>
        </svg>
    ) : (
        <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round"
                  d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z"/>
        </svg>
    );
}

function FolderIcon() {
    return (
        <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round"
                  d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z"/>
        </svg>
    );
}

// ---------- main app ----------

export function App() {
    const [state, setState] = useState<AppState>("idle");
    const [transcript, setTranscript] = useState<TranscriptData | null>(null);
    const [error, setError] = useState<ApiError | null>(null);
    const [selectedRange, setSelectedRange] = useState<[number, number] | null>(null);
    const [cleanFillers, setCleanFillers] = useState(false);
    const [modal, setModal] = useState<Modal>(null);
    const [prefsVersion, setPrefsVersion] = useState(0);
    const [isSaved, setIsSaved] = useState(false);
    const [tags, setTags] = useState<string[]>([]);
    const [selectedLang, setSelectedLang] = useState<string | null>(null);
    const [highlights, setHighlights] = useState<number[]>([]);
    const [notes, setNotes] = useState<NoteEntry[]>([]);
    const [batchState, setBatchState] = useState<BatchState | null>(null);
    const [batchViewMode, setBatchViewMode] = useState<"progress" | "result">("progress");
    const [route, setRoute] = useState<string>(window.location.hash);
    const [currentTime, setCurrentTime] = useState(0);
    const lastFetchRef = useRef(0);
    const batchRef = useRef<BatchProcessor | null>(null);

    // Shim YTPlayer interface using message-based currentTime
    const playerRef = useRef<YTPlayer | null>(null);
    useEffect(() => {
        playerRef.current = {
            seekTo: (seconds: number) => {
                chrome.runtime.sendMessage({type: "seek-to", time: seconds}).catch(() => {});
            },
            getCurrentTime: () => currentTime,
            getPlayerState: () => 1, // PLAYING
        };
    }, [currentTime]);

    // Listen for video-info messages from content script (via background)
    useEffect(() => {
        const listener = (message: { type: string; videoId?: string }) => {
            if (message.type === "video-info" && message.videoId) {
                void fetchTranscript(message.videoId);
            }
        };
        chrome.runtime.onMessage.addListener(listener);
        return () => chrome.runtime.onMessage.removeListener(listener);
    }, []);

    // Listen for player-time messages from content script
    useEffect(() => {
        const listener = (message: { type: string; currentTime?: number }) => {
            if (message.type === "player-time" && message.currentTime !== undefined) {
                setCurrentTime(message.currentTime);
            }
        };
        chrome.runtime.onMessage.addListener(listener);
        return () => chrome.runtime.onMessage.removeListener(listener);
    }, []);

    // Hash-based routing
    useEffect(() => {
        const handler = () => setRoute(window.location.hash);
        window.addEventListener("hashchange", handler);
        return () => window.removeEventListener("hashchange", handler);
    }, []);

    // Load saved data (highlights, notes, tags) when transcript changes
    useEffect(() => {
        if (transcript) {
            getSavedTranscript(transcript.videoId).then((saved) => {
                setIsSaved(!!saved);
                setTags(saved?.tags ?? []);
                setHighlights(saved?.highlights ?? []);
                setNotes(saved?.notes ?? []);
            });
        } else {
            setIsSaved(false);
            setTags([]);
            setHighlights([]);
            setNotes([]);
        }
    }, [transcript?.videoId]);

    // Fetch transcript via extension message passing
    const fetchTranscript = useCallback(async (videoId: string, lang?: string, translateTo?: string) => {
        const now = Date.now();
        const elapsed = now - lastFetchRef.current;
        if (elapsed < 2000) {
            await new Promise((r) => setTimeout(r, 2000 - elapsed));
        }
        lastFetchRef.current = Date.now();

        setState("loading");
        setError(null);
        setSelectedRange(null);

        try {
            const response = await chrome.runtime.sendMessage({
                type: "fetch-transcript",
                videoId,
                ...(lang ? {lang} : {}),
                ...(translateTo ? {translateTo} : {}),
            }) as { type: string; data?: TranscriptData; error?: ApiError };

            if (response.type === "transcript-error" && response.error) {
                setError(response.error);
                setState("error");
                return;
            }

            if (response.type === "transcript-result" && response.data) {
                const td = response.data;
                setTranscript(td);
                setState("loaded");

                const wordCount = td.segments.reduce(
                    (sum, s) => sum + s.text.split(/\s+/).filter((w) => w.length > 0).length,
                    0,
                );
                void addToHistory({
                    videoId: td.videoId,
                    title: td.title,
                    language: td.language,
                    thumbnailUrl: `https://img.youtube.com/vi/${td.videoId}/mqdefault.jpg`,
                    fetchedAt: new Date().toISOString(),
                    segmentCount: td.segments.length,
                    wordCount,
                });
            }
        } catch {
            setError({error: "fetch_failed", message: "Failed to fetch transcript. Please try again."});
            setState("error");
        }
    }, []);

    const handleSeek = useCallback((seconds: number) => {
        chrome.runtime.sendMessage({type: "seek-to", time: seconds}).catch(() => {});
    }, []);

    const handleSave = useCallback(async () => {
        if (!transcript) return;
        await saveTranscript({
            videoId: transcript.videoId,
            title: transcript.title,
            language: transcript.language,
            isAutoGenerated: transcript.isAutoGenerated,
            segments: transcript.segments,
            savedAt: new Date().toISOString(),
            highlights: [],
            notes: [],
            tags: [],
        });
        setIsSaved(true);
    }, [transcript]);

    const handleLoadSaved = useCallback((saved: SavedTranscript) => {
        setTranscript({
            videoId: saved.videoId,
            title: saved.title,
            language: saved.language,
            isAutoGenerated: saved.isAutoGenerated,
            tracks: [],
            segments: saved.segments,
        });
        setState("loaded");
        setIsSaved(true);
    }, []);

    const handlePreferencesChange = useCallback((_prefs: Preferences) => {
        setPrefsVersion((v) => v + 1);
    }, []);

    const handleRetry = useCallback(() => {
        setState("idle");
        setError(null);
    }, []);

    const handleLanguageChange = useCallback((langCode: string) => {
        if (!transcript) return;
        setSelectedLang(langCode);
        void fetchTranscript(transcript.videoId, langCode);
    }, [transcript, fetchTranscript]);

    const handleTagsChange = useCallback((newTags: string[]) => {
        if (!transcript) return;
        setTags(newTags);
        void updateTags(transcript.videoId, newTags);
    }, [transcript]);

    const handleHighlightToggle = useCallback((segmentIndex: number) => {
        if (!transcript || !isSaved) return;
        setHighlights(prev => {
            const next = prev.includes(segmentIndex)
                ? prev.filter(i => i !== segmentIndex)
                : [...prev, segmentIndex];
            void updateHighlights(transcript.videoId, next);
            return next;
        });
    }, [transcript, isSaved]);

    const handleNoteUpdate = useCallback((segmentIndex: number, text: string) => {
        if (!transcript || !isSaved) return;
        setNotes(prev => {
            const filtered = prev.filter(n => n.segmentIndex !== segmentIndex);
            const next = text.trim()
                ? [...filtered, {segmentIndex, text: text.trim(), createdAt: new Date().toISOString()}]
                : filtered;
            void updateNotes(transcript.videoId, next);
            return next;
        });
    }, [transcript, isSaved]);

    // ---------- batch handlers ----------

    const handleSubmitBatch = useCallback((videoIds: string[]) => {
        const processor = new BatchProcessor();
        batchRef.current = processor;
        processor.onProgress = (s) => setBatchState(s);
        processor.start(videoIds);
        setBatchViewMode("progress");
    }, []);

    const handleBatchViewResult = useCallback((videoId: string) => {
        const item = batchState?.items.find(i => i.videoId === videoId);
        if (item?.result) {
            setTranscript({
                videoId: item.result.videoId,
                title: item.result.title,
                language: item.result.language,
                isAutoGenerated: item.result.isAutoGenerated,
                tracks: item.result.tracks,
                segments: item.result.segments,
            });
            setState("loaded");
            setBatchViewMode("result");
        }
    }, [batchState]);

    const handleBackToBatch = useCallback(() => {
        setBatchViewMode("progress");
        setState("idle");
        setTranscript(null);
    }, []);

    const handleBatchCancel = useCallback(() => {
        batchRef.current?.cancel();
    }, []);

    const handleBatchRetry = useCallback(() => {
        batchRef.current?.retryFailed();
    }, []);

    const handleBatchExport = useCallback((format: string, mode: "separate" | "merged") => {
        if (!batchState || !batchRef.current) return;
        if (mode === "merged") batchRef.current.exportMerged(batchState.items, format);
        else batchRef.current.exportAsZip(batchState.items, format);
    }, [batchState]);

    const batchCompletedItems = useMemo(() => {
        if (!batchState) return [];
        return batchState.items
            .filter((i): i is BatchItem & {result: TranscriptResponse} => i.status === "success" && !!i.result)
            .map(i => ({videoId: i.videoId, title: i.title ?? i.videoId}));
    }, [batchState]);

    const iconBtnClass = "rounded-lg p-1.5 text-slate-500 hover:bg-slate-100 hover:text-slate-700 dark:text-slate-400 dark:hover:bg-slate-700 dark:hover:text-slate-200 transition-colors";

    // ---------- legal page route ----------
    if (route === "#/legal") {
        return (
            <div className="min-h-screen bg-white dark:bg-slate-900">
                <header
                    className="border-b border-slate-200 bg-white/80 backdrop-blur dark:border-slate-700 dark:bg-slate-900/80">
                    <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-2">
                        <span className="text-sm font-bold text-slate-900 dark:text-white">YT Transcript</span>
                    </div>
                </header>
                <Suspense fallback={null}>
                    <LegalPage onBack={() => {
                        window.location.hash = "";
                        setRoute("");
                    }}/>
                </Suspense>
            </div>
        );
    }

    // ---------- main app route ----------
    return (
        <div className="min-h-screen bg-white dark:bg-slate-900">
            {/* Header */}
            <header
                className="border-b border-slate-200 bg-white/80 backdrop-blur dark:border-slate-700 dark:bg-slate-900/80">
                <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-2">
                    <span className="text-sm font-bold text-slate-900 dark:text-white">YT Transcript</span>
                    <div className="flex items-center gap-1">
                        {state === "loaded" && (
                            <button
                                onClick={handleSave}
                                title={isSaved ? "Saved" : "Save transcript"}
                                className={iconBtnClass}
                                disabled={isSaved}
                            >
                                <BookmarkIcon filled={isSaved}/>
                            </button>
                        )}
                        <button onClick={() => setModal("history")} title="History" className={iconBtnClass}>
                            <ClockIcon/>
                        </button>
                        <button onClick={() => setModal("saved")} title="Saved transcripts" className={iconBtnClass}>
                            <FolderIcon/>
                        </button>
                        <button onClick={() => setModal("settings")} title="Settings" className={iconBtnClass}>
                            <GearIcon/>
                        </button>
                    </div>
                </div>
            </header>

            {/* Main content */}
            <div className="mx-auto max-w-5xl px-4 py-6">
                <UrlInput
                    onSubmit={(id) => void fetchTranscript(id)}
                    onSubmitBatch={handleSubmitBatch}
                    isLoading={state === "loading"}
                    hasTranscript={state === "loaded" || state === "loading"}
                />

                {batchState && batchViewMode === "result" && batchCompletedItems.length > 0 && (
                    <BatchResultsNav
                        items={batchCompletedItems}
                        activeVideoId={transcript?.videoId ?? null}
                        onSelect={handleBatchViewResult}
                        onBackToBatch={handleBackToBatch}
                    />
                )}

                {batchState && batchViewMode === "progress" && (
                    <Suspense fallback={<div className="h-32 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>}>
                        <BatchProgress
                            batchState={batchState}
                            onRetry={handleBatchRetry}
                            onCancel={handleBatchCancel}
                            onViewResult={handleBatchViewResult}
                            onExport={handleBatchExport}
                        />
                    </Suspense>
                )}

                {state === "loading" && <LoadingSpinner/>}

                {state === "error" && error && (
                    <ErrorMessage error={error.error} message={error.message} onRetry={handleRetry}/>
                )}

                {state === "loaded" && transcript && (
                    <div className="space-y-4">
                        {/* Tags */}
                        {isSaved && (
                            <div className="max-w-md">
                                <TagEditor tags={tags} onTagsChange={handleTagsChange} />
                            </div>
                        )}

                        {/* Language selector */}
                        {transcript.tracks.length > 1 && (
                            <div className="max-w-xs">
                                <label className="block text-xs font-medium text-slate-600 dark:text-slate-400 mb-1">
                                    Language
                                </label>
                                <select
                                    value={selectedLang ?? transcript.language}
                                    onChange={(e) => handleLanguageChange(e.target.value)}
                                    className="w-full rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200"
                                >
                                    {transcript.tracks.map((track) => (
                                        <option key={track.languageCode} value={track.languageCode}>
                                            {track.name} {track.kind === "asr" ? "(auto)" : ""}
                                        </option>
                                    ))}
                                </select>
                            </div>
                        )}

                        {/* Transcript */}
                        <TranscriptView
                            key={prefsVersion}
                            segments={transcript.segments}
                            title={transcript.title}
                            language={transcript.language}
                            isAutoGenerated={transcript.isAutoGenerated}
                            playerRef={playerRef}
                            selectedRange={selectedRange}
                            onSelectedRangeChange={setSelectedRange}
                            cleanFillers={cleanFillers}
                            onCleanFillersChange={setCleanFillers}
                            chapters={transcript.chapters}
                            highlights={highlights}
                            notes={notes}
                            onHighlightToggle={isSaved ? handleHighlightToggle : undefined}
                            onNoteUpdate={isSaved ? handleNoteUpdate : undefined}
                        />

                        {/* Export bar */}
                        <ExportBar
                            segments={transcript.segments}
                            title={transcript.title}
                            language={transcript.language}
                            videoId={transcript.videoId}
                            isAutoGenerated={transcript.isAutoGenerated}
                            showTimestamps={true}
                            selectedRange={selectedRange}
                            cleanFillers={cleanFillers}
                        />

                        {/* AI Panel */}
                        <Suspense
                            fallback={<div className="h-32 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800"/>}>
                            <AiPanel transcript={transcript as TranscriptResponse} onSeek={handleSeek}/>
                        </Suspense>
                    </div>
                )}
            </div>

            {/* Modals */}
            <Suspense fallback={null}>
                <Settings
                    isOpen={modal === "settings"}
                    onClose={() => setModal(null)}
                    onPreferencesChange={handlePreferencesChange}
                />
                <History
                    isOpen={modal === "history"}
                    onClose={() => setModal(null)}
                    onSelectVideo={(videoId) => {
                        setModal(null);
                        void fetchTranscript(videoId);
                    }}
                />
                <SavedList
                    isOpen={modal === "saved"}
                    onClose={() => setModal(null)}
                    onLoadSaved={handleLoadSaved}
                />
            </Suspense>

            {/* Footer */}
            <footer className="mt-8 border-t border-slate-200 dark:border-slate-700">
                <div className="mx-auto max-w-5xl px-4 py-4 text-center text-xs text-slate-500 dark:text-slate-400">
                    <a href="#/legal" className="hover:text-slate-700 dark:hover:text-slate-300 underline">
                        Legal & Privacy
                    </a>
                </div>
            </footer>
        </div>
    );
}
