import {useCallback, useMemo, useState} from "react";
import type {Chapter, Segment} from "../types/transcript";
import {formatTimestamp} from "../lib/formatTime";
import {exportTxt, generateTxt} from "../lib/exportTxt";
import {exportSrt} from "../lib/exportSrt";
import {exportVtt} from "../lib/exportVtt";
import {exportCsv} from "../lib/exportCsv";
import {exportJson} from "../lib/exportJson";
import {exportMarkdown, generateMarkdown} from "../lib/exportMarkdown";
import {removeFillersFromSegments} from "../lib/cleanText";

interface ExportBarProps {
    segments: Segment[];
    title: string;
    language: string;
    videoId: string;
    isAutoGenerated: boolean;
    showTimestamps: boolean;
    selectedRange: [number, number] | null;
    cleanFillers?: boolean;
    chapters?: Chapter[];
    highlights?: number[];
}

export function ExportBar({
                              segments,
                              title,
                              language,
                              videoId,
                              isAutoGenerated,
                              showTimestamps,
                              selectedRange,
                              cleanFillers,
                              chapters,
                              highlights,
                          }: ExportBarProps) {
    const [copied, setCopied] = useState<string | null>(null);
    const [showMore, setShowMore] = useState(false);

    let activeSegments = selectedRange
        ? segments.slice(selectedRange[0], selectedRange[1] + 1)
        : segments;
    if (cleanFillers) {
        activeSegments = removeFillersFromSegments(activeSegments, language);
    }

    const handleCopy = useCallback(async () => {
        const text = generateTxt(activeSegments, showTimestamps);
        await navigator.clipboard.writeText(text);
        setCopied("copy");
        setTimeout(() => setCopied(null), 2000);
    }, [activeSegments, showTimestamps]);

    const handleCopyNotion = useCallback(async () => {
        const text = generateMarkdown({title, videoId, language, segments: activeSegments, chapters, format: "notion"});
        await navigator.clipboard.writeText(text);
        setCopied("notion");
        setTimeout(() => setCopied(null), 2000);
    }, [activeSegments, title, videoId, language, chapters]);

    const handleCopyObsidian = useCallback(async () => {
        const text = generateMarkdown({title, videoId, language, segments: activeSegments, chapters, format: "obsidian"});
        await navigator.clipboard.writeText(text);
        setCopied("obsidian");
        setTimeout(() => setCopied(null), 2000);
    }, [activeSegments, title, videoId, language, chapters]);

    // Highlights use original segment indices (from IndexedDB), so filter from
    // the raw segments array and apply cleanFillers independently.
    const highlightedSegments = useMemo(() => {
        if (!highlights || highlights.length === 0) return [];
        let result = segments.filter((_, i) => highlights.includes(i));
        if (cleanFillers) result = removeFillersFromSegments(result, language);
        return result;
    }, [segments, highlights, cleanFillers, language]);

    const handleCopyHighlights = useCallback(async () => {
        const text = generateTxt(highlightedSegments, showTimestamps);
        await navigator.clipboard.writeText(text);
        setCopied("highlights");
        setTimeout(() => setCopied(null), 2000);
    }, [highlightedSegments, showTimestamps]);

    const btnClass =
        "min-h-[36px] rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 shadow-xs transition-colors hover:bg-slate-50 focus:outline-hidden focus:ring-2 focus:ring-blue-500 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700";

    return (
        <div className="flex flex-wrap items-center gap-2">
            {selectedRange && (
                <span
                    className="mr-1 rounded-full bg-blue-100 px-2.5 py-1 text-xs font-medium text-blue-700 dark:bg-blue-900/40 dark:text-blue-300">
          {formatTimestamp(activeSegments[0]?.start ?? 0)} - {formatTimestamp(activeSegments[activeSegments.length - 1]?.start ?? 0)}
                    {" "}({activeSegments.length} segments)
        </span>
            )}

            <button onClick={handleCopy} className={btnClass}>
                {copied === "copy" ? "Copied" : "Copy"}
            </button>
            {highlightedSegments.length > 0 && (
                <button onClick={handleCopyHighlights} className={btnClass}>
                    {copied === "highlights" ? "Copied" : `Highlights (${highlightedSegments.length})`}
                </button>
            )}
            <button onClick={() => exportTxt(activeSegments, title, language, showTimestamps)} className={btnClass}>
                TXT
            </button>
            <button onClick={() => exportSrt(activeSegments, title, language)} className={btnClass}>
                SRT
            </button>

            {/* Extra formats: visible on desktop, dropdown on mobile */}
            <div className="hidden gap-2 sm:flex">
                <button onClick={() => exportVtt(activeSegments, title, language)} className={btnClass}>VTT</button>
                <button
                    onClick={() => exportJson({videoId, title, language, isAutoGenerated, segments: activeSegments})}
                    className={btnClass}>JSON
                </button>
                <button onClick={() => exportCsv(activeSegments, title, language)} className={btnClass}>CSV</button>
                <button onClick={() => exportMarkdown({title, videoId, language, segments: activeSegments, chapters})}
                        className={btnClass}>MD
                </button>
                <button onClick={handleCopyNotion}
                        className={btnClass}>{copied === "notion" ? "Copied" : "Notion"}</button>
                <button onClick={handleCopyObsidian}
                        className={btnClass}>{copied === "obsidian" ? "Copied" : "Obsidian"}</button>
            </div>

            {/* Mobile overflow */}
            <div className="relative sm:hidden">
                <button onClick={() => setShowMore(!showMore)} className={btnClass}>
                    More...
                </button>
                {showMore && (
                    <div
                        className="absolute right-0 top-full z-10 mt-1 flex flex-col gap-1 rounded-lg border border-slate-200 bg-white p-2 shadow-lg dark:border-slate-600 dark:bg-slate-800">
                        <button onClick={() => {
                            exportVtt(activeSegments, title, language);
                            setShowMore(false);
                        }} className={btnClass}>VTT
                        </button>
                        <button onClick={() => {
                            exportJson({videoId, title, language, isAutoGenerated, segments: activeSegments});
                            setShowMore(false);
                        }} className={btnClass}>JSON
                        </button>
                        <button onClick={() => {
                            exportCsv(activeSegments, title, language);
                            setShowMore(false);
                        }} className={btnClass}>CSV
                        </button>
                        <button onClick={() => {
                            exportMarkdown({title, videoId, language, segments: activeSegments, chapters});
                            setShowMore(false);
                        }} className={btnClass}>MD
                        </button>
                        <button onClick={() => {
                            void handleCopyNotion();
                            setShowMore(false);
                        }} className={btnClass}>Notion
                        </button>
                        <button onClick={() => {
                            void handleCopyObsidian();
                            setShowMore(false);
                        }} className={btnClass}>Obsidian
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
}
