import {useCallback, useMemo, useState} from "react";
import type {Chapter, Segment} from "../types/transcript";
import {exportTxt, generateTxt} from "../lib/exportTxt";
import {exportSrt} from "../lib/exportSrt";
import {exportVtt} from "../lib/exportVtt";
import {exportCsv} from "../lib/exportCsv";
import {exportJson} from "../lib/exportJson";
import {exportMarkdown, generateMarkdown} from "../lib/exportMarkdown";
import {removeFillersFromSegments} from "../lib/cleanText";

interface ExportBarProps {
    segments: Segment[];
    title: string;
    language: string;
    videoId: string;
    isAutoGenerated: boolean;
    showTimestamps: boolean;
    cleanFillers?: boolean;
    chapters?: Chapter[];
    highlights?: number[];
}

// One-stop format menu — every export channel lives behind a single
// disclosure rather than fighting "Copy" for primacy. Order: clipboard
// targets first, file downloads after.
type FormatRow =
    | { kind: "copy"; id: string; label: string; run: () => Promise<void> | void }
    | { kind: "download"; label: string; run: () => void };

export function ExportBar({
                              segments,
                              title,
                              language,
                              videoId,
                              isAutoGenerated,
                              showTimestamps,
                              cleanFillers,
                              chapters,
                              highlights,
                          }: ExportBarProps) {
    const [copied, setCopied] = useState<string | null>(null);

    const activeSegments = cleanFillers
        ? removeFillersFromSegments(segments, language)
        : segments;

    const flashCopied = useCallback((id: string) => {
        setCopied(id);
        setTimeout(() => setCopied(null), 1800);
    }, []);

    const handleCopyPlain = useCallback(async () => {
        await navigator.clipboard.writeText(generateTxt(activeSegments, showTimestamps));
        flashCopied("plain");
    }, [activeSegments, showTimestamps, flashCopied]);

    const handleCopyNotion = useCallback(async () => {
        await navigator.clipboard.writeText(
            generateMarkdown({title, videoId, language, segments: activeSegments, chapters, format: "notion"}),
        );
        flashCopied("notion");
    }, [activeSegments, title, videoId, language, chapters, flashCopied]);

    const handleCopyObsidian = useCallback(async () => {
        await navigator.clipboard.writeText(
            generateMarkdown({title, videoId, language, segments: activeSegments, chapters, format: "obsidian"}),
        );
        flashCopied("obsidian");
    }, [activeSegments, title, videoId, language, chapters, flashCopied]);

    const highlightedSegments = useMemo(() => {
        if (!highlights || highlights.length === 0) return [];
        let result = segments.filter((_, i) => highlights.includes(i));
        if (cleanFillers) result = removeFillersFromSegments(result, language);
        return result;
    }, [segments, highlights, cleanFillers, language]);

    const handleCopyHighlights = useCallback(async () => {
        await navigator.clipboard.writeText(generateTxt(highlightedSegments, showTimestamps));
        flashCopied("highlights");
    }, [highlightedSegments, showTimestamps, flashCopied]);

    const formatRows: FormatRow[] = [
        {kind: "copy", id: "notion", label: "Copy as Notion", run: handleCopyNotion},
        {kind: "copy", id: "obsidian", label: "Copy as Obsidian", run: handleCopyObsidian},
        {kind: "download", label: "Download .txt", run: () => exportTxt(activeSegments, title, language, showTimestamps)},
        {kind: "download", label: "Download .srt", run: () => exportSrt(activeSegments, title, language)},
        {kind: "download", label: "Download .vtt", run: () => exportVtt(activeSegments, title, language)},
        {kind: "download", label: "Download .json", run: () => exportJson({videoId, title, language, isAutoGenerated, segments: activeSegments})},
        {kind: "download", label: "Download .csv", run: () => exportCsv(activeSegments, title, language)},
        {kind: "download", label: "Download .md", run: () => exportMarkdown({title, videoId, language, segments: activeSegments, chapters})},
    ];

    return (
        <div className="space-y-2">
            <div className="flex items-center gap-1.5">
                <button
                    onClick={() => void handleCopyPlain()}
                    className="group flex h-9 flex-1 items-center justify-center gap-2 rounded-md border border-slate-300/80 bg-white text-[13px] font-medium text-slate-800 transition hover:border-slate-400 hover:bg-slate-50 dark:border-slate-700/80 dark:bg-slate-900 dark:text-slate-100 dark:hover:border-slate-600 dark:hover:bg-slate-800"
                >
                    <svg className="h-3.5 w-3.5 text-slate-500 group-hover:text-slate-700 dark:text-slate-400 dark:group-hover:text-slate-200" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.75}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/>
                    </svg>
                    {copied === "plain" ? "Copied" : "Copy"}
                </button>

                {highlightedSegments.length > 0 && (
                    <button
                        onClick={() => void handleCopyHighlights()}
                        title="Copy highlights only"
                        className="h-9 rounded-md border border-amber-300/60 bg-amber-50 px-2.5 text-[12px] font-medium text-amber-800 hover:border-amber-400/80 dark:border-amber-300/20 dark:bg-amber-300/5 dark:text-amber-300 dark:hover:border-amber-300/40"
                    >
                        {copied === "highlights" ? "Copied" : `★ ${highlightedSegments.length}`}
                    </button>
                )}

                <details className="relative">
                    <summary className="flex h-9 cursor-pointer list-none items-center gap-1 rounded-md border border-slate-300/80 bg-white px-2.5 text-[12px] font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50 dark:border-slate-700/80 dark:bg-slate-900 dark:text-slate-300 dark:hover:border-slate-600 dark:hover:bg-slate-800">
                        Export
                        <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7"/>
                        </svg>
                    </summary>
                    <div className="absolute right-0 z-30 mt-1 min-w-[180px] rounded-md border border-slate-200 bg-white p-1 shadow-lg dark:border-slate-700 dark:bg-slate-900">
                        {formatRows.map((row, i) => (
                            <button
                                key={i}
                                onClick={(e) => {
                                    void row.run();
                                    const parent = (e.currentTarget as HTMLElement).closest("details");
                                    if (parent) parent.removeAttribute("open");
                                }}
                                className="flex w-full items-center justify-between rounded px-2.5 py-1.5 text-left text-[12px] text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"
                            >
                                <span>{row.label}</span>
                                {row.kind === "copy" && copied === row.id && (
                                    <span className="font-mono text-[10px] text-amber-600 dark:text-amber-400">copied</span>
                                )}
                            </button>
                        ))}
                    </div>
                </details>
            </div>
        </div>
    );
}
