import {type KeyboardEvent, useCallback, useEffect, useMemo, useRef, useState,} from "react";
import {useVirtualizer} from "@tanstack/react-virtual";
import type {Chapter, NoteEntry, Segment} from "../types/transcript";
import {formatTimestamp} from "../lib/formatTime";
import {mergeIntoParagraphs, mergeIntoSentences} from "../lib/mergeSegments";
import {removeFillersFromSegments} from "../lib/cleanText";
import {getPreferences} from "../lib/storage/preferences";
import {detectSpeakers, getUniqueSpeakers, filterBySpeaker, type SegmentWithSpeaker} from "../lib/detectSpeakers";

// ---------- types ----------

type ViewMode = "raw" | "sentences" | "paragraphs";

interface TranscriptViewProps {
    segments: Segment[];
    title: string;
    language: string;
    isAutoGenerated: boolean;
    playerRef: React.RefObject<YTPlayer | null>;
    selectedRange: [number, number] | null;
    onSelectedRangeChange: (range: [number, number] | null) => void;
    cleanFillers: boolean;
    onCleanFillersChange: (value: boolean) => void;
    chapters?: Chapter[];
    highlights?: number[];
    notes?: NoteEntry[];
    onHighlightToggle?: (segmentIndex: number) => void;
    onNoteUpdate?: (segmentIndex: number, text: string) => void;
}

interface YTPlayer {
    seekTo: (seconds: number, allowSeekAhead: boolean) => void;
    getCurrentTime: () => number;
    getPlayerState: () => number;
}

// ---------- helpers ----------

function useDebounce(value: string, ms: number): string {
    const [debounced, setDebounced] = useState(value);
    useEffect(() => {
        const id = setTimeout(() => setDebounced(value), ms);
        return () => clearTimeout(id);
    }, [value, ms]);
    return debounced;
}

function highlightText(text: string, query: string): React.ReactNode {
    if (query.length === 0) return text;
    const escaped = query.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const parts = text.split(new RegExp(`(${escaped})`, "gi"));
    return parts.map((part, i) =>
        part.toLowerCase() === query.toLowerCase() ? (
            <mark key={i} className="search-highlight">
                {part}
            </mark>
        ) : (
            part
        ),
    );
}

function countWords(segments: Segment[]): number {
    return segments.reduce(
        (sum, s) => sum + s.text.split(/\s+/).filter((w) => w.length > 0).length,
        0,
    );
}

function matchesSearch(text: string, query: string): boolean {
    return query.length === 0 || text.toLowerCase().includes(query.toLowerCase());
}

// ---------- speaker colors ----------

const SPEAKER_COLORS = [
    "text-blue-600 dark:text-blue-400",
    "text-emerald-600 dark:text-emerald-400",
    "text-purple-600 dark:text-purple-400",
    "text-orange-600 dark:text-orange-400",
    "text-pink-600 dark:text-pink-400",
    "text-teal-600 dark:text-teal-400",
    "text-red-600 dark:text-red-400",
    "text-indigo-600 dark:text-indigo-400",
];

function getSpeakerColor(speaker: string, speakers: string[]): string {
    const idx = speakers.indexOf(speaker);
    return SPEAKER_COLORS[idx % SPEAKER_COLORS.length] ?? SPEAKER_COLORS[0]!;
}

// ---------- component ----------

export function TranscriptView({
                                   segments,
                                   title,
                                   language,
                                   isAutoGenerated,
                                   playerRef,
                                   selectedRange,
                                   onSelectedRangeChange,
                                   cleanFillers,
                                   onCleanFillersChange,
                                   chapters,
                                   highlights,
                                   notes,
                                   onHighlightToggle,
                                   onNoteUpdate,
                               }: TranscriptViewProps) {
    const [viewMode, setViewMode] = useState<ViewMode>("raw");
    const [showTimestamps, setShowTimestamps] = useState(true);
    const [compactMode, setCompactMode] = useState(false);
    const [searchQuery, setSearchQuery] = useState("");
    const [autoScroll, setAutoScroll] = useState(true);

    useEffect(() => {
        void getPreferences().then((p) => {
            setViewMode(p.viewMode);
            setShowTimestamps(p.showTimestamps);
            setCompactMode(p.compactMode);
            setAutoScroll(p.autoScroll);
        });
    }, []);
    const [activeIndex, setActiveIndex] = useState(-1);
    const [rangeAnchor, setRangeAnchor] = useState<number | null>(null);
    const [editingNoteIndex, setEditingNoteIndex] = useState<number | null>(null);
    const [noteText, setNoteText] = useState("");
    const [collapsedChapters, setCollapsedChapters] = useState<Set<number>>(new Set());

    const debouncedQuery = useDebounce(searchQuery, 200);
    const scrollContainerRef = useRef<HTMLDivElement>(null);
    const autoScrollIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

    // Note lookup map
    const noteMap = useMemo(() => {
        const map = new Map<number, string>();
        if (notes) {
            for (const note of notes) {
                map.set(note.segmentIndex, note.text);
            }
        }
        return map;
    }, [notes]);

    // Merge segments based on view mode, then optionally clean fillers
    const displaySegments = useMemo((): Segment[] => {
        let result: Segment[];
        switch (viewMode) {
            case "sentences":
                result = mergeIntoSentences(segments);
                break;
            case "paragraphs":
                result = mergeIntoParagraphs(segments).map((p) => ({
                    start: p.start,
                    duration: p.duration,
                    text: p.text,
                }));
                break;
            default:
                result = segments;
        }
        if (cleanFillers) {
            result = removeFillersFromSegments(result, language);
        }
        return result;
    }, [segments, viewMode, cleanFillers, language]);

    // Speaker detection
    const speakerSegments = useMemo((): SegmentWithSpeaker[] => {
        return detectSpeakers(displaySegments);
    }, [displaySegments]);

    const uniqueSpeakers = useMemo((): string[] => {
        return getUniqueSpeakers(speakerSegments);
    }, [speakerSegments]);

    const [speakerFilter, setSpeakerFilter] = useState<string | null>(null);

    const filteredSegments = useMemo((): SegmentWithSpeaker[] => {
        if (!speakerFilter) return speakerSegments;
        return filterBySpeaker(speakerSegments, speakerFilter);
    }, [speakerSegments, speakerFilter]);

    // Chapter map: segment index -> chapter, and chapter ranges for collapsibility
    const chapterMap = useMemo(() => {
        if (!chapters || chapters.length === 0) return new Map<number, Chapter>();
        const map = new Map<number, Chapter>();
        for (const chapter of chapters) {
            let bestIdx = 0;
            let bestDiff = Infinity;
            for (let i = 0; i < filteredSegments.length; i++) {
                const diff = Math.abs(filteredSegments[i]!.start - chapter.start);
                if (diff < bestDiff) {
                    bestDiff = diff;
                    bestIdx = i;
                }
            }
            map.set(bestIdx, chapter);
        }
        return map;
    }, [chapters, filteredSegments]);

    // Compute body-segment indices hidden by collapsed chapters (headers stay visible)
    const collapsedIndices = useMemo(() => {
        if (collapsedChapters.size === 0 || chapterMap.size === 0) return new Set<number>();
        const hidden = new Set<number>();
        const chapterStarts = [...chapterMap.keys()].sort((a, b) => a - b);
        for (let ci = 0; ci < chapterStarts.length; ci++) {
            const startIdx = chapterStarts[ci]!;
            if (!collapsedChapters.has(startIdx)) continue;
            // Hide body segments (startIdx+1..endIdx), keep header (startIdx) visible
            const endIdx = ci + 1 < chapterStarts.length ? chapterStarts[ci + 1]! : filteredSegments.length;
            for (let i = startIdx + 1; i < endIdx; i++) hidden.add(i);
        }
        return hidden;
    }, [collapsedChapters, chapterMap, filteredSegments.length]);

    const toggleChapter = useCallback((chapterIdx: number) => {
        setCollapsedChapters(prev => {
            const next = new Set(prev);
            if (next.has(chapterIdx)) next.delete(chapterIdx);
            else next.add(chapterIdx);
            return next;
        });
    }, []);

    // Search match tracking
    const matchCount = useMemo(() => {
        if (debouncedQuery.length === 0) return 0;
        return filteredSegments.filter((s) => matchesSearch(s.text, debouncedQuery)).length;
    }, [filteredSegments, debouncedQuery]);

    const wordCount = useMemo(() => countWords(segments), [segments]);

    // Visible indices: all segments except body segments hidden by collapsed chapters
    const visibleIndices = useMemo(() => {
        if (collapsedIndices.size === 0) return filteredSegments.map((_, i) => i);
        return filteredSegments.map((_, i) => i).filter(i => !collapsedIndices.has(i));
    }, [filteredSegments, collapsedIndices]);

    // Virtual scrolling
    const virtualizer = useVirtualizer({
        count: visibleIndices.length,
        getScrollElement: () => scrollContainerRef.current,
        estimateSize: () => (compactMode ? 32 : viewMode === "paragraphs" ? 80 : 44),
        overscan: 20,
    });

    // Auto-scroll with player
    useEffect(() => {
        if (!autoScroll) {
            if (autoScrollIntervalRef.current) {
                clearInterval(autoScrollIntervalRef.current);
                autoScrollIntervalRef.current = null;
            }
            return;
        }

        autoScrollIntervalRef.current = setInterval(() => {
            const player = playerRef.current;
            if (!player) return;
            try {
                const state = player.getPlayerState();
                if (state !== 1) return; // 1 = playing
                const currentTime = player.getCurrentTime();
                let idx = -1;
                for (let i = filteredSegments.length - 1; i >= 0; i--) {
                    if (filteredSegments[i]!.start <= currentTime) {
                        idx = i;
                        break;
                    }
                }
                if (idx >= 0 && idx !== activeIndex) {
                    setActiveIndex(idx);
                    const vIdx = visibleIndices.indexOf(idx);
                    if (vIdx >= 0) virtualizer.scrollToIndex(vIdx, {align: "center"});
                }
            } catch {
                // Player not ready
            }
        }, 500);

        return () => {
            if (autoScrollIntervalRef.current) {
                clearInterval(autoScrollIntervalRef.current);
            }
        };
    }, [autoScroll, filteredSegments, playerRef, activeIndex, virtualizer, visibleIndices]);

    // Click-to-seek
    const handleSegmentClick = useCallback(
        (index: number, e: React.MouseEvent) => {
            const segment = filteredSegments[index];
            if (!segment) return;

            // Shift+Click for range selection
            if (e.shiftKey && rangeAnchor !== null) {
                const start = Math.min(rangeAnchor, index);
                const end = Math.max(rangeAnchor, index);
                onSelectedRangeChange([start, end]);
                return;
            }

            // Normal click: seek and set anchor
            setRangeAnchor(index);
            onSelectedRangeChange(null);

            const player = playerRef.current;
            if (player) {
                try {
                    player.seekTo(segment.start, true);
                } catch {
                    // Player not ready
                }
            }
        },
        [filteredSegments, playerRef, rangeAnchor, onSelectedRangeChange],
    );

    // Keyboard navigation
    const handleKeyDown = useCallback(
        (e: KeyboardEvent) => {
            if (e.ctrlKey && e.key === "f") {
                e.preventDefault();
                document.getElementById("transcript-search")?.focus();
                return;
            }

            switch (e.key) {
                case "ArrowDown": {
                    e.preventDefault();
                    const next = Math.min(activeIndex + 1, filteredSegments.length - 1);
                    setActiveIndex(next);
                    const vNext = visibleIndices.indexOf(next);
                    if (vNext >= 0) virtualizer.scrollToIndex(vNext, {align: "center"});
                    break;
                }
                case "ArrowUp": {
                    e.preventDefault();
                    const prev = Math.max(activeIndex - 1, 0);
                    setActiveIndex(prev);
                    const vPrev = visibleIndices.indexOf(prev);
                    if (vPrev >= 0) virtualizer.scrollToIndex(vPrev, {align: "center"});
                    break;
                }
                case "Enter": {
                    const seg = filteredSegments[activeIndex];
                    if (seg) {
                        playerRef.current?.seekTo(seg.start, true);
                    }
                    break;
                }
                case "Escape":
                    onSelectedRangeChange(null);
                    setRangeAnchor(null);
                    break;
            }
        },
        [activeIndex, filteredSegments, playerRef, onSelectedRangeChange, virtualizer, visibleIndices],
    );

    const isInRange = useCallback(
        (index: number) => {
            if (!selectedRange) return false;
            return index >= selectedRange[0] && index <= selectedRange[1];
        },
        [selectedRange],
    );

    return (
        <div className="flex flex-col" onKeyDown={handleKeyDown} tabIndex={0}>
            {/* Header: title + metadata */}
            <div className="mb-3">
                <h2 className="text-xl font-bold text-slate-900 dark:text-slate-100">{title}</h2>
                <div className="mt-1.5 flex flex-wrap items-center gap-2 text-sm">
          <span
              className="rounded-full bg-slate-100 px-2.5 py-0.5 font-medium text-slate-700 dark:bg-slate-700 dark:text-slate-300">
            {language}
          </span>
                    <span
                        className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${
                            isAutoGenerated
                                ? "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300"
                                : "bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300"
                        }`}
                    >
            {isAutoGenerated ? "Auto-generated" : "Manual"}
          </span>
                    <span className="text-slate-500 dark:text-slate-400">
            {displaySegments.length} segments
          </span>
                    <span className="text-slate-500 dark:text-slate-400">
            ~{wordCount.toLocaleString()} words
          </span>
                </div>
            </div>

            {/* Toolbar: view mode, search, toggles */}
            <div className="mb-3 flex flex-wrap items-center gap-2">
                {/* View mode selector */}
                <div className="flex rounded-lg border border-slate-200 dark:border-slate-600">
                    {(["raw", "sentences", "paragraphs"] as const).map((mode) => (
                        <button
                            key={mode}
                            onClick={() => setViewMode(mode)}
                            className={`px-3 py-1.5 text-xs font-medium capitalize transition-colors first:rounded-l-lg last:rounded-r-lg ${
                                viewMode === mode
                                    ? "bg-blue-600 text-white dark:bg-blue-500"
                                    : "bg-white text-slate-600 hover:bg-slate-50 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700"
                            }`}
                        >
                            {mode}
                        </button>
                    ))}
                </div>

                {/* Search */}
                <div className="relative flex-1 sm:max-w-xs">
                    <input
                        id="transcript-search"
                        type="text"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        placeholder="Search transcript..."
                        aria-label="Search transcript"
                        className="h-8 w-full rounded-lg border border-slate-200 bg-white px-3 pr-16 text-xs shadow-xs placeholder:text-slate-400 focus:outline-hidden focus:ring-2 focus:ring-blue-500 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-100 dark:placeholder:text-slate-500"
                    />
                    {debouncedQuery.length > 0 && (
                        <span
                            className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-slate-500 dark:text-slate-400"
                            aria-live="polite">
              {matchCount} match{matchCount !== 1 ? "es" : ""}
            </span>
                    )}
                </div>

                {/* Toggles */}
                <label className="flex cursor-pointer items-center gap-1.5 text-xs text-slate-600 dark:text-slate-400">
                    <input type="checkbox" checked={showTimestamps}
                           onChange={(e) => setShowTimestamps(e.target.checked)} className="rounded-sm"/>
                    Timestamps
                </label>
                <label className="flex cursor-pointer items-center gap-1.5 text-xs text-slate-600 dark:text-slate-400">
                    <input type="checkbox" checked={compactMode} onChange={(e) => setCompactMode(e.target.checked)}
                           className="rounded-sm"/>
                    Compact
                </label>
                <label className="flex cursor-pointer items-center gap-1.5 text-xs text-slate-600 dark:text-slate-400">
                    <input type="checkbox" checked={autoScroll} onChange={(e) => setAutoScroll(e.target.checked)}
                           className="rounded-sm"/>
                    Auto-scroll
                </label>
                <label className="flex cursor-pointer items-center gap-1.5 text-xs text-slate-600 dark:text-slate-400">
                    <input type="checkbox" checked={cleanFillers} onChange={(e) => onCleanFillersChange(e.target.checked)}
                           className="rounded-sm"/>
                    Clean fillers
                </label>
                {uniqueSpeakers.length > 1 && (
                    <select
                        value={speakerFilter ?? ""}
                        onChange={(e) => setSpeakerFilter(e.target.value || null)}
                        className="h-8 rounded-lg border border-slate-200 bg-white px-2 text-xs dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200"
                    >
                        <option value="">All speakers</option>
                        {uniqueSpeakers.map((s) => (
                            <option key={s} value={s}>{s}</option>
                        ))}
                    </select>
                )}
            </div>

            {/* Transcript list (virtualized) */}
            <div
                ref={scrollContainerRef}
                className="max-h-[70vh] overflow-y-auto rounded-lg border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800/50"
                role="list"
                aria-label="Transcript segments"
            >
                <div
                    style={{height: virtualizer.getTotalSize(), position: "relative"}}
                >
                    {virtualizer.getVirtualItems().map((virtualRow) => {
                        const segIdx = visibleIndices[virtualRow.index]!;
                        const segment = filteredSegments[segIdx];
                        if (!segment) return null;

                        const isCollapsedHeader = chapterMap.has(segIdx) && collapsedChapters.has(segIdx);
                        const matches = matchesSearch(segment.text, debouncedQuery);
                        const isActive = segIdx === activeIndex;
                        const inRange = isInRange(segIdx);
                        const isHighlighted = highlights?.includes(segIdx) ?? false;
                        const existingNote = noteMap.get(segIdx);
                        const isEditingNote = editingNoteIndex === segIdx;

                        return (
                            <div
                                key={virtualRow.key}
                                data-index={virtualRow.index}
                                ref={virtualizer.measureElement}
                                role="listitem"
                                onClick={(e) => handleSegmentClick(segIdx, e)}
                                style={{
                                    position: "absolute",
                                    top: 0,
                                    left: 0,
                                    width: "100%",
                                    transform: `translateY(${String(virtualRow.start)}px)`,
                                }}
                                className={`group cursor-pointer border-l-3 px-3 transition-colors ${
                                    compactMode ? "py-0.5" : "py-2"
                                } ${isHighlighted ? "border-yellow-400 bg-yellow-50/50 dark:bg-yellow-900/10" : "border-transparent"} ${
                                    isActive ? "segment-active" : ""
                                } ${inRange ? "segment-selected" : ""} ${
                                    debouncedQuery.length > 0 && !matches
                                        ? "opacity-30"
                                        : "hover:bg-slate-50 dark:hover:bg-slate-700/50"
                                }`}
                            >
                                {chapterMap.has(segIdx) && (
                                    <button
                                        type="button"
                                        onClick={(e) => { e.stopPropagation(); toggleChapter(segIdx); }}
                                        className="mb-1 flex w-full items-center gap-1 border-t border-slate-300 pt-2 text-left dark:border-slate-600"
                                    >
                                        <svg className={`h-3 w-3 shrink-0 text-slate-400 transition-transform ${collapsedChapters.has(segIdx) ? "" : "rotate-90"}`} viewBox="0 0 24 24" fill="currentColor">
                                            <path d="M9 5l7 7-7 7z"/>
                                        </svg>
                                        <span className="text-xs font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400">
                                            {chapterMap.get(segIdx)!.title}
                                        </span>
                                    </button>
                                )}
                                {!isCollapsedHeader && (<>
                                <div className="flex gap-2">
                                    {showTimestamps && (
                                        <span
                                            className="shrink-0 select-none font-mono text-xs text-slate-400 dark:text-slate-500">
                      [{formatTimestamp(segment.start)}]
                    </span>
                                    )}
                                    {segment.speaker && uniqueSpeakers.length > 1 && (
                                        <span className={`shrink-0 text-xs font-semibold ${getSpeakerColor(segment.speaker, uniqueSpeakers)}`}>
                      {segment.speaker}:
                    </span>
                                    )}
                                    <span
                                        className={`text-sm leading-relaxed text-slate-800 dark:text-slate-200 ${
                                            viewMode === "paragraphs" ? "whitespace-pre-wrap" : ""
                                        }`}
                                    >
                    {highlightText(segment.text, debouncedQuery)}
                  </span>
                                    {/* Highlight and note buttons */}
                                    {onHighlightToggle && (
                                        <div className="ml-auto flex shrink-0 gap-1 opacity-0 transition-opacity group-hover:opacity-100">
                                            <button
                                                type="button"
                                                onClick={(e) => { e.stopPropagation(); onHighlightToggle(segIdx); }}
                                                className={`rounded-sm p-0.5 ${isHighlighted ? "text-yellow-500" : "text-slate-400 hover:text-yellow-500"}`}
                                                title={isHighlighted ? "Remove highlight" : "Highlight"}
                                            >
                                                <svg className="h-3.5 w-3.5" fill={isHighlighted ? "currentColor" : "none"} viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                                    <path strokeLinecap="round" strokeLinejoin="round" d="M9.53 16.122a3 3 0 00-5.78 1.128 2.25 2.25 0 01-2.4 2.245 4.5 4.5 0 008.4-2.245c0-.399-.078-.78-.22-1.128zm0 0a15.998 15.998 0 003.388-1.62m-5.043-.025a15.994 15.994 0 011.622-3.395m3.42 3.42a15.995 15.995 0 004.764-4.648l3.876-5.814a1.151 1.151 0 00-1.597-1.597L14.146 6.32a15.996 15.996 0 00-4.649 4.763m3.42 3.42a6.776 6.776 0 00-3.42-3.42" />
                                                </svg>
                                            </button>
                                            <button
                                                type="button"
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    if (isEditingNote) {
                                                        setEditingNoteIndex(null);
                                                    } else {
                                                        setEditingNoteIndex(segIdx);
                                                        setNoteText(existingNote ?? "");
                                                    }
                                                }}
                                                className={`rounded-sm p-0.5 ${existingNote !== undefined ? "text-blue-500" : "text-slate-400 hover:text-blue-500"}`}
                                                title="Add note"
                                            >
                                                <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                                    <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
                                                </svg>
                                            </button>
                                        </div>
                                    )}
                                </div>

                                {/* Inline note editor */}
                                {isEditingNote && onNoteUpdate && (
                                    <div className="ml-8 mt-1" onClick={(e) => e.stopPropagation()}>
                                        <textarea
                                            value={noteText}
                                            onChange={(e) => setNoteText(e.target.value)}
                                            placeholder="Add a note..."
                                            className="w-full rounded-sm border border-slate-200 bg-white p-2 text-xs focus:outline-hidden focus:ring-1 focus:ring-blue-500 dark:border-slate-600 dark:bg-slate-700 dark:text-slate-200"
                                            rows={2}
                                            autoFocus
                                        />
                                        <div className="mt-1 flex gap-1">
                                            <button type="button"
                                                onClick={() => { onNoteUpdate(segIdx, noteText); setEditingNoteIndex(null); }}
                                                className="rounded-sm bg-blue-600 px-2 py-0.5 text-xs text-white hover:bg-blue-700">Save</button>
                                            <button type="button"
                                                onClick={() => setEditingNoteIndex(null)}
                                                className="rounded-sm px-2 py-0.5 text-xs text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-700">Cancel</button>
                                        </div>
                                    </div>
                                )}

                                {/* Note indicator if note exists but editor not open */}
                                {existingNote !== undefined && !isEditingNote && (
                                    <div className="ml-8 mt-0.5 truncate text-xs italic text-blue-600 dark:text-blue-400">
                                        {existingNote}
                                    </div>
                                )}
                                </>)}
                            </div>
                        );
                    })}
                </div>
            </div>
        </div>
    );
}
