import {type KeyboardEvent, useCallback, useEffect, useMemo, useRef, useState} from "react";
import {useVirtualizer} from "@tanstack/react-virtual";
import type {NoteEntry, Segment} from "../types/transcript";
import {formatTimestamp} from "../lib/formatTime";
import {mergeIntoParagraphs} from "../lib/mergeSegments";
import {removeFillersFromSegments} from "../lib/cleanText";

interface YTPlayer {
    seekTo: (seconds: number, allowSeekAhead: boolean) => void;
    getCurrentTime: () => number;
    getPlayerState: () => number;
}

interface TranscriptViewProps {
    segments: Segment[];
    title: string;
    language: string;
    isAutoGenerated: boolean;
    playerRef: React.RefObject<YTPlayer | null>;
    cleanFillers: boolean;
    onCleanFillersChange: (value: boolean) => void;
    highlights?: number[];
    notes?: NoteEntry[];
    onHighlightToggle?: (segmentIndex: number) => void;
    onNoteUpdate?: (segmentIndex: number, text: string) => void;
}

function useDebounce(value: string, ms: number): string {
    const [debounced, setDebounced] = useState(value);
    useEffect(() => {
        const id = setTimeout(() => setDebounced(value), ms);
        return () => clearTimeout(id);
    }, [value, ms]);
    return debounced;
}

function highlightText(text: string, query: string): React.ReactNode {
    if (query.length === 0) return text;
    const escaped = query.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const parts = text.split(new RegExp(`(${escaped})`, "gi"));
    return parts.map((part, i) =>
        part.toLowerCase() === query.toLowerCase()
            ? <mark key={i} className="search-highlight">{part}</mark>
            : part,
    );
}

function countWords(segments: Segment[]): number {
    return segments.reduce(
        (sum, s) => sum + s.text.split(/\s+/).filter((w) => w.length > 0).length,
        0,
    );
}

function matchesSearch(text: string, query: string): boolean {
    return query.length === 0 || text.toLowerCase().includes(query.toLowerCase());
}

export function TranscriptView({
                                   segments,
                                   title,
                                   language,
                                   isAutoGenerated,
                                   playerRef,
                                   cleanFillers,
                                   onCleanFillersChange,
                                   highlights,
                                   notes,
                                   onHighlightToggle,
                                   onNoteUpdate,
                               }: TranscriptViewProps) {
    const [searchQuery, setSearchQuery] = useState("");
    const [editingNoteIndex, setEditingNoteIndex] = useState<number | null>(null);
    const [noteText, setNoteText] = useState("");

    const debouncedQuery = useDebounce(searchQuery, 200);
    const scrollContainerRef = useRef<HTMLDivElement>(null);

    const noteMap = useMemo(() => {
        const map = new Map<number, string>();
        if (notes) {
            for (const note of notes) map.set(note.segmentIndex, note.text);
        }
        return map;
    }, [notes]);

    // One canonical view: paragraphs. Optional filler-word cleanup is the
    // only transformation that's meaningfully different from YouTube's own
    // transcript panel.
    const displaySegments = useMemo((): Segment[] => {
        const paragraphs = mergeIntoParagraphs(segments).map((p) => ({
            start: p.start,
            duration: p.duration,
            text: p.text,
        }));
        return cleanFillers ? removeFillersFromSegments(paragraphs, language) : paragraphs;
    }, [segments, cleanFillers, language]);

    const matchCount = useMemo(() => {
        if (debouncedQuery.length === 0) return 0;
        return displaySegments.filter((s) => matchesSearch(s.text, debouncedQuery)).length;
    }, [displaySegments, debouncedQuery]);

    const wordCount = useMemo(() => countWords(segments), [segments]);
    const totalDuration = useMemo(() => {
        if (segments.length === 0) return 0;
        const last = segments[segments.length - 1]!;
        return last.start + last.duration;
    }, [segments]);

    const virtualizer = useVirtualizer({
        count: displaySegments.length,
        getScrollElement: () => scrollContainerRef.current,
        estimateSize: () => 88,
        overscan: 10,
    });

    const handleSegmentClick = useCallback((index: number) => {
        const segment = displaySegments[index];
        if (!segment) return;
        try {
            playerRef.current?.seekTo(segment.start, true);
        } catch {
            // Player not ready
        }
    }, [displaySegments, playerRef]);

    // Ctrl+F focuses the search box. That's the only keyboard shortcut left —
    // arrow-key segment navigation was a YouTube duplicate and got cut.
    const handleKeyDown = useCallback((e: KeyboardEvent) => {
        if ((e.ctrlKey || e.metaKey) && e.key === "f") {
            e.preventDefault();
            document.getElementById("transcript-search")?.focus();
        }
    }, []);

    return (
        <div className="flex flex-col" onKeyDown={handleKeyDown} tabIndex={0}>
            {/* Title + meta */}
            <div className="mb-3">
                <h2 className="font-serif text-[19px] leading-[1.2] tracking-[-0.01em] text-slate-900 dark:text-slate-50">
                    {title}
                </h2>
                <p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-slate-500 dark:text-slate-500">
                    <span className="tabular-nums">{formatTimestamp(totalDuration)}</span>
                    <span className="mx-1.5 text-slate-400 dark:text-slate-700">·</span>
                    <span className="tabular-nums">{wordCount.toLocaleString()}w</span>
                    <span className="mx-1.5 text-slate-400 dark:text-slate-700">·</span>
                    <span>{language}</span>
                    {isAutoGenerated && (
                        <>
                            <span className="mx-1.5 text-slate-400 dark:text-slate-700">·</span>
                            <span className="text-slate-400 dark:text-slate-600">asr</span>
                        </>
                    )}
                </p>
            </div>

            {/* Search + filler toggle on a single row */}
            <div className="mb-3 flex items-center gap-2">
                <div className="relative flex-1">
                    <svg className="pointer-events-none absolute left-2 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400 dark:text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-4.35-4.35M11 19a8 8 0 110-16 8 8 0 010 16z"/>
                    </svg>
                    <input
                        id="transcript-search"
                        type="text"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        placeholder="Search transcript"
                        aria-label="Search transcript"
                        className="h-8 w-full rounded-md border border-slate-200 bg-white pl-7 pr-12 text-[12px] placeholder:text-slate-400 focus:border-slate-400 focus:outline-hidden dark:border-slate-800 dark:bg-slate-900/40 dark:text-slate-100 dark:placeholder:text-slate-600 dark:focus:border-slate-600"
                    />
                    {debouncedQuery.length > 0 && (
                        <span className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 font-mono text-[10px] tabular-nums text-amber-600 dark:text-amber-400" aria-live="polite">
                            {matchCount}
                        </span>
                    )}
                </div>
                <label className="flex shrink-0 cursor-pointer items-center gap-1.5 text-[11px] text-slate-600 dark:text-slate-400">
                    <input
                        type="checkbox"
                        checked={cleanFillers}
                        onChange={(e) => onCleanFillersChange(e.target.checked)}
                        className="h-3.5 w-3.5 rounded-sm accent-slate-900 dark:accent-white"
                    />
                    Clean fillers
                </label>
            </div>

            {/* Virtualized paragraph list */}
            <div
                ref={scrollContainerRef}
                className="max-h-[70vh] overflow-y-auto rounded-lg border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800/50"
                role="list"
                aria-label="Transcript segments"
            >
                <div style={{height: virtualizer.getTotalSize(), position: "relative"}}>
                    {virtualizer.getVirtualItems().map((virtualRow) => {
                        const segIdx = virtualRow.index;
                        const segment = displaySegments[segIdx];
                        if (!segment) return null;

                        const matches = matchesSearch(segment.text, debouncedQuery);
                        const isHighlighted = highlights?.includes(segIdx) ?? false;
                        const existingNote = noteMap.get(segIdx);
                        const isEditingNote = editingNoteIndex === segIdx;

                        return (
                            <div
                                key={virtualRow.key}
                                data-index={virtualRow.index}
                                ref={virtualizer.measureElement}
                                role="listitem"
                                onClick={() => handleSegmentClick(segIdx)}
                                style={{
                                    position: "absolute",
                                    top: 0,
                                    left: 0,
                                    width: "100%",
                                    transform: `translateY(${String(virtualRow.start)}px)`,
                                }}
                                className={`group cursor-pointer border-l-3 px-3 py-2 transition-colors ${
                                    isHighlighted
                                        ? "border-yellow-400 bg-yellow-50/50 dark:bg-yellow-900/10"
                                        : "border-transparent"
                                } ${
                                    debouncedQuery.length > 0 && !matches
                                        ? "opacity-30"
                                        : "hover:bg-slate-50 dark:hover:bg-slate-700/50"
                                }`}
                            >
                                <div className="flex gap-2.5">
                                    <span className="shrink-0 select-none pt-[3px] font-mono text-[10px] tabular-nums text-slate-400 dark:text-slate-600">
                                        {formatTimestamp(segment.start)}
                                    </span>
                                    <span className="whitespace-pre-wrap text-[13.5px] leading-[1.55] text-slate-800 dark:text-slate-200">
                                        {highlightText(segment.text, debouncedQuery)}
                                    </span>
                                    {onHighlightToggle && (
                                        <div className="ml-auto flex shrink-0 gap-1 opacity-0 transition-opacity group-hover:opacity-100">
                                            <button
                                                type="button"
                                                onClick={(e) => { e.stopPropagation(); onHighlightToggle(segIdx); }}
                                                className={`rounded-sm p-0.5 ${isHighlighted ? "text-yellow-500" : "text-slate-400 hover:text-yellow-500"}`}
                                                title={isHighlighted ? "Remove highlight" : "Highlight"}
                                            >
                                                <svg className="h-3.5 w-3.5" fill={isHighlighted ? "currentColor" : "none"} viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                                    <path strokeLinecap="round" strokeLinejoin="round" d="M9.53 16.122a3 3 0 00-5.78 1.128 2.25 2.25 0 01-2.4 2.245 4.5 4.5 0 008.4-2.245c0-.399-.078-.78-.22-1.128zm0 0a15.998 15.998 0 003.388-1.62m-5.043-.025a15.994 15.994 0 011.622-3.395m3.42 3.42a15.995 15.995 0 004.764-4.648l3.876-5.814a1.151 1.151 0 00-1.597-1.597L14.146 6.32a15.996 15.996 0 00-4.649 4.763m3.42 3.42a6.776 6.776 0 00-3.42-3.42"/>
                                                </svg>
                                            </button>
                                            <button
                                                type="button"
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    if (isEditingNote) {
                                                        setEditingNoteIndex(null);
                                                    } else {
                                                        setEditingNoteIndex(segIdx);
                                                        setNoteText(existingNote ?? "");
                                                    }
                                                }}
                                                className={`rounded-sm p-0.5 ${existingNote !== undefined ? "text-slate-700 dark:text-slate-200" : "text-slate-400 hover:text-slate-700 dark:hover:text-slate-200"}`}
                                                title="Add note"
                                            >
                                                <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                                    <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"/>
                                                </svg>
                                            </button>
                                        </div>
                                    )}
                                </div>

                                {isEditingNote && onNoteUpdate && (
                                    <div className="ml-8 mt-1" onClick={(e) => e.stopPropagation()}>
                                        <textarea
                                            value={noteText}
                                            onChange={(e) => setNoteText(e.target.value)}
                                            placeholder="Add a note..."
                                            className="w-full rounded-sm border border-slate-200 bg-white p-2 text-xs focus:outline-hidden focus:ring-1 focus:ring-blue-500 dark:border-slate-600 dark:bg-slate-700 dark:text-slate-200"
                                            rows={2}
                                            autoFocus
                                        />
                                        <div className="mt-1 flex gap-1">
                                            <button
                                                type="button"
                                                onClick={() => { onNoteUpdate(segIdx, noteText); setEditingNoteIndex(null); }}
                                                className="rounded-md bg-slate-900 px-2.5 py-0.5 text-xs text-white hover:bg-slate-800 dark:bg-white dark:text-slate-900 dark:hover:bg-slate-200"
                                            >
                                                Save
                                            </button>
                                            <button
                                                type="button"
                                                onClick={() => setEditingNoteIndex(null)}
                                                className="rounded-sm px-2 py-0.5 text-xs text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-700"
                                            >
                                                Cancel
                                            </button>
                                        </div>
                                    </div>
                                )}

                                {existingNote !== undefined && !isEditingNote && (
                                    <div className="ml-8 mt-1 border-l-2 border-slate-300 pl-2 text-xs text-slate-600 dark:border-slate-700 dark:text-slate-400">
                                        {existingNote}
                                    </div>
                                )}
                            </div>
                        );
                    })}
                </div>
            </div>
        </div>
    );
}
