import type { Chapter, Segment, TranscriptResponse, Track } from "@/types/transcript";
import { extractPlayerResult } from "@/background/innertube";
import { parseChapters } from "@/lib/parseChapters";

interface PlayerSnapshot {
  title: string;
  tracks: Track[];
  isAutoGenerated: boolean;
  language: string;
  shortDescription: string;
}

interface TabState {
  videoId: string | null;
  player: PlayerSnapshot | null;
  segments: Segment[] | null;
  emittedFor: string | null;
}

const tabs = new Map<number, TabState>();

let lastBroadcastTabId: number | null = null;

export function getBroadcastingTabId(): number | null {
  return lastBroadcastTabId;
}

export function recordBroadcast(tabId: number): void {
  lastBroadcastTabId = tabId;
}

function ensure(tabId: number): TabState {
  let s = tabs.get(tabId);
  if (!s) {
    s = { videoId: null, player: null, segments: null, emittedFor: null };
    tabs.set(tabId, s);
  }
  return s;
}

function reset(state: TabState, videoId: string): void {
  state.videoId = videoId;
  state.player = null;
  state.segments = null;
  state.emittedFor = null;
}

export function clearTab(tabId: number): void {
  tabs.delete(tabId);
  if (lastBroadcastTabId === tabId) lastBroadcastTabId = null;
}

function buildPlayerSnapshot(rawJson: string, userAgent: string): PlayerSnapshot | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawJson);
  } catch {
    return null;
  }
  const result = extractPlayerResult(parsed, userAgent);
  if ("error" in result) return null;

  const defaultLang = (((parsed as Record<string, unknown>)["videoDetails"] as
    Record<string, unknown> | undefined)?.["defaultAudioLanguage"] as string | undefined)
    ?.split("-")[0]?.toLowerCase();
  const ordered = [...result.captionTracks].sort((a, b) => {
    const aMatch = defaultLang && a.languageCode.toLowerCase().startsWith(defaultLang) ? 1 : 0;
    const bMatch = defaultLang && b.languageCode.toLowerCase().startsWith(defaultLang) ? 1 : 0;
    if (aMatch !== bMatch) return bMatch - aMatch;
    const aAsr = a.kind === "asr" ? 1 : 0;
    const bAsr = b.kind === "asr" ? 1 : 0;
    return bAsr - aAsr;
  });

  const tracks: Track[] = ordered.map((t) => ({
    languageCode: t.languageCode,
    name:
      typeof t.name?.simpleText === "string" && t.name.simpleText.length > 0
        ? t.name.simpleText
        : t.languageCode,
    kind: t.kind,
  }));

  const first = ordered[0];
  return {
    title: result.title,
    tracks,
    isAutoGenerated: first?.kind === "asr",
    language: first?.languageCode ?? "en",
    shortDescription: result.shortDescription,
  };
}

export function recordPlayer(tabId: number, videoId: string, rawJson: string): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  const snap = buildPlayerSnapshot(rawJson, "Mozilla/5.0");
  if (snap) state.player = snap;
}

export function recordTimedText(tabId: number, videoId: string, bodyText: string): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  if (!bodyText.trim() || (state.segments && state.segments.length > 0)) return;
  let parsed: unknown;
  try { parsed = JSON.parse(bodyText); } catch { return; }
  if (typeof parsed !== "object" || parsed === null) return;
  const events = (parsed as Record<string, unknown>)["events"];
  if (!Array.isArray(events)) return;
  const segs: Segment[] = [];
  for (const ev of events) {
    if (typeof ev !== "object" || ev === null) continue;
    const e = ev as { tStartMs?: number; dDurationMs?: number; segs?: { utf8?: string }[] };
    if (!Array.isArray(e.segs) || e.segs.length === 0) continue;
    const text = e.segs.map((s) => s.utf8 ?? "").join("").trim();
    if (!text) continue;
    segs.push({
      start: (e.tStartMs ?? 0) / 1000,
      duration: (e.dDurationMs ?? 0) / 1000,
      text,
    });
  }
  if (segs.length > 0) state.segments = segs;
}

export function takeIfReady(
  tabId: number,
  options: { force?: boolean } = {},
): TranscriptResponse | null {
  const state = tabs.get(tabId);
  if (!state || !state.videoId) return null;
  if (!state.segments || state.segments.length === 0) return null;

  const player = state.player;
  const language = player?.language ?? "en";
  const title = player?.title ?? state.videoId;
  const tracks = player?.tracks ?? [];
  const isAutoGenerated = player?.isAutoGenerated ?? false;
  const chapters: Chapter[] = player ? parseChapters(player.shortDescription) : [];

  const response: TranscriptResponse = {
    videoId: state.videoId,
    title,
    language,
    isAutoGenerated,
    tracks,
    segments: state.segments,
    ...(chapters.length > 0 && { chapters }),
  };

  if (!options.force && state.emittedFor === state.videoId) return null;
  state.emittedFor = state.videoId;
  return response;
}
