// Service-worker-side correlator for intercepted YouTube responses.
// One entry per tab. Combines a `player` capture (title, tracks,
// chapters) with a `get_transcript` capture (segments) into a single
// TranscriptResponse and emits it to the side panel as soon as both
// halves are present.
//
// State lives only in memory on the service worker. It is cleared on
// SW restart, on tab close, and when a tab navigates to a new
// videoId. Nothing persists.

import type { Chapter, Segment, TranscriptResponse, Track } from "@/types/transcript";
import { extractPlayerResult } from "@/background/innertube";
import { parseChapters } from "@/lib/parseChapters";
import { parseGetTranscript } from "./parseGetTranscript";

interface PlayerSnapshot {
  title: string;
  tracks: Track[];
  isAutoGenerated: boolean;
  language: string;
  shortDescription: string;
}

interface TabState {
  videoId: string | null;
  player: PlayerSnapshot | null;
  segments: Segment[] | null;
  // The last response we emitted, to avoid duplicate broadcasts.
  emittedFor: string | null;
}

const tabs = new Map<number, TabState>();

function ensure(tabId: number): TabState {
  let s = tabs.get(tabId);
  if (!s) {
    s = { videoId: null, player: null, segments: null, emittedFor: null };
    tabs.set(tabId, s);
  }
  return s;
}

function reset(state: TabState, videoId: string): void {
  state.videoId = videoId;
  state.player = null;
  state.segments = null;
  state.emittedFor = null;
}

export function clearTab(tabId: number): void {
  tabs.delete(tabId);
}

export function notifyNavigate(tabId: number, videoId: string | null): void {
  if (!videoId) return;
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
}

function buildPlayerSnapshot(rawJson: string, userAgent: string): PlayerSnapshot | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawJson);
  } catch {
    return null;
  }
  const result = extractPlayerResult(parsed, userAgent);
  if ("error" in result) return null;

  const tracks: Track[] = result.captionTracks.map((t) => ({
    languageCode: t.languageCode,
    name:
      typeof t.name?.simpleText === "string" && t.name.simpleText.length > 0
        ? t.name.simpleText
        : t.languageCode,
    kind: t.kind,
  }));

  const first = result.captionTracks[0];
  return {
    title: result.title,
    tracks,
    isAutoGenerated: first?.kind === "asr",
    language: first?.languageCode ?? "en",
    shortDescription: result.shortDescription,
  };
}

export function recordPlayer(tabId: number, videoId: string, rawJson: string): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  const snap = buildPlayerSnapshot(rawJson, "Mozilla/5.0");
  if (snap) state.player = snap;
}

export function recordTranscript(tabId: number, videoId: string, bodyText: string): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  const segs = parseGetTranscript(bodyText);
  if (segs.length > 0) state.segments = segs;
}

// timedtext is a fallback. It's the legacy /api/timedtext json3 shape;
// we already have a parser for that. Wire it in later if needed —
// get_transcript covers the cases that broke us.
export function recordTimedText(tabId: number, videoId: string, _bodyText: string): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  // Reserved for future use; the get_transcript parser is the
  // primary path.
}

export function takeIfReady(
  tabId: number,
  options: { force?: boolean } = {},
): TranscriptResponse | null {
  const state = tabs.get(tabId);
  if (!state || !state.videoId) return null;
  if (!state.segments || state.segments.length === 0) return null;

  // Without a player snapshot we can still emit using fallbacks.
  const player = state.player;
  const language = player?.language ?? "en";
  const title = player?.title ?? state.videoId;
  const tracks = player?.tracks ?? [];
  const isAutoGenerated = player?.isAutoGenerated ?? false;
  const chapters: Chapter[] = player ? parseChapters(player.shortDescription) : [];

  const response: TranscriptResponse = {
    videoId: state.videoId,
    title,
    language,
    isAutoGenerated,
    tracks,
    segments: state.segments,
    ...(chapters.length > 0 && { chapters }),
  };

  if (!options.force && state.emittedFor === state.videoId) return null;
  state.emittedFor = state.videoId;
  return response;
}
