// Service-worker-side correlator for intercepted YouTube responses.
// One entry per tab. Combines a `player` capture (title, tracks,
// chapters) with a `get_transcript` capture (segments) into a single
// TranscriptResponse and emits it to the side panel as soon as both
// halves are present.
//
// State lives only in memory on the service worker. It is cleared on
// SW restart, on tab close, and when a tab navigates to a new
// videoId. Nothing persists.

import type { Chapter, Segment, TranscriptResponse, Track } from "@/types/transcript";
import { extractPlayerResult } from "@/background/innertube";
import { parseChapters } from "@/lib/parseChapters";
import { parseGetTranscript } from "./parseGetTranscript";

interface CaptionTrackUrl {
  baseUrl: string;
  languageCode: string;
  kind?: string;
}

interface PlayerSnapshot {
  title: string;
  tracks: Track[];
  isAutoGenerated: boolean;
  language: string;
  shortDescription: string;
  captionTrackUrls: CaptionTrackUrl[];
}

interface TabState {
  videoId: string | null;
  player: PlayerSnapshot | null;
  segments: Segment[] | null;
  // The last response we emitted, to avoid duplicate broadcasts.
  emittedFor: string | null;
  // Marks an in-flight auto-fetch from a captured captionTrack baseUrl
  // so we don't kick off duplicate requests on every player heartbeat.
  autoFetching: boolean;
}

const tabs = new Map<number, TabState>();

function ensure(tabId: number): TabState {
  let s = tabs.get(tabId);
  if (!s) {
    s = { videoId: null, player: null, segments: null, emittedFor: null, autoFetching: false };
    tabs.set(tabId, s);
  }
  return s;
}

function reset(state: TabState, videoId: string): void {
  state.videoId = videoId;
  state.player = null;
  state.segments = null;
  state.emittedFor = null;
  state.autoFetching = false;
}

export function clearTab(tabId: number): void {
  tabs.delete(tabId);
}

export function notifyNavigate(tabId: number, videoId: string | null): void {
  if (!videoId) return;
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
}

function buildPlayerSnapshot(rawJson: string, userAgent: string): PlayerSnapshot | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawJson);
  } catch {
    return null;
  }
  const result = extractPlayerResult(parsed, userAgent);
  if ("error" in result) return null;

  // Reorder so the original-language track is first. YouTube ships
  // captionTracks ordered by the user's UI locale, which means a German
  // browser sees a German auto-translation as tracks[0] for an English
  // video — surprising and wrong as a default selection.
  const defaultLang = (((parsed as Record<string, unknown>)["videoDetails"] as
    Record<string, unknown> | undefined)?.["defaultAudioLanguage"] as string | undefined)
    ?.split("-")[0]?.toLowerCase();
  const ordered = [...result.captionTracks].sort((a, b) => {
    const aMatch = defaultLang && a.languageCode.toLowerCase().startsWith(defaultLang) ? 1 : 0;
    const bMatch = defaultLang && b.languageCode.toLowerCase().startsWith(defaultLang) ? 1 : 0;
    if (aMatch !== bMatch) return bMatch - aMatch;
    const aAsr = a.kind === "asr" ? 1 : 0;
    const bAsr = b.kind === "asr" ? 1 : 0;
    return bAsr - aAsr;
  });

  const tracks: Track[] = ordered.map((t) => ({
    languageCode: t.languageCode,
    name:
      typeof t.name?.simpleText === "string" && t.name.simpleText.length > 0
        ? t.name.simpleText
        : t.languageCode,
    kind: t.kind,
  }));

  const captionTrackUrls: CaptionTrackUrl[] = ordered.map((t) => ({
    baseUrl: t.baseUrl,
    languageCode: t.languageCode,
    ...(t.kind ? { kind: t.kind } : {}),
  }));

  const first = ordered[0];
  return {
    title: result.title,
    tracks,
    isAutoGenerated: first?.kind === "asr",
    language: first?.languageCode ?? "en",
    shortDescription: result.shortDescription,
    captionTrackUrls,
  };
}

export function recordPlayer(tabId: number, videoId: string, rawJson: string): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  const snap = buildPlayerSnapshot(rawJson, "Mozilla/5.0");
  if (snap) state.player = snap;
}

export function recordTranscript(tabId: number, videoId: string, bodyText: string): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  const segs = parseGetTranscript(bodyText);
  if (segs.length > 0) state.segments = segs;
}

// timedtext is the legacy /api/timedtext json3 shape — used by the
// content script's page-context fetch (which inherits the YouTube
// session's PO token, so &exp=xpe-signed URLs return real content
// instead of empty bodies).
export function recordTimedText(tabId: number, videoId: string, bodyText: string): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  if (!bodyText.trim() || (state.segments && state.segments.length > 0)) return;
  let parsed: unknown;
  try { parsed = JSON.parse(bodyText); } catch { return; }
  if (typeof parsed !== "object" || parsed === null) return;
  const events = (parsed as Record<string, unknown>)["events"];
  if (!Array.isArray(events)) return;
  const segs: Segment[] = [];
  for (const ev of events) {
    if (typeof ev !== "object" || ev === null) continue;
    const e = ev as { tStartMs?: number; dDurationMs?: number; segs?: { utf8?: string }[] };
    if (!Array.isArray(e.segs) || e.segs.length === 0) continue;
    const text = e.segs.map((s) => s.utf8 ?? "").join("").trim();
    if (!text) continue;
    segs.push({
      start: (e.tStartMs ?? 0) / 1000,
      duration: (e.dDurationMs ?? 0) / 1000,
      text,
    });
  }
  if (segs.length > 0) state.segments = segs;
}

// Used by the SW auto-fetch path (intercepted player capture →
// fetch captionTrack baseUrl → populate segments) to seed the
// correlator without going through get_transcript.
export function recordAutoFetchedSegments(
  tabId: number,
  videoId: string,
  segments: Segment[],
): void {
  const state = ensure(tabId);
  if (state.videoId !== videoId) reset(state, videoId);
  if (segments.length > 0 && (!state.segments || state.segments.length === 0)) {
    state.segments = segments;
  }
  state.autoFetching = false;
}

// Returns the first track baseUrl for this tab, or null if we don't
// have a player capture yet, already have segments, or are mid-fetch.
// Sets autoFetching=true so callers can fan out exactly once.
export function claimAutoFetchTrack(
  tabId: number,
  videoId: string,
): { baseUrl: string; languageCode: string } | null {
  const state = tabs.get(tabId);
  if (!state || state.videoId !== videoId) return null;
  if (state.autoFetching) return null;
  if (state.segments && state.segments.length > 0) return null;
  const player = state.player;
  if (!player || player.captionTrackUrls.length === 0) return null;
  const first = player.captionTrackUrls[0];
  if (!first) return null;
  state.autoFetching = true;
  return { baseUrl: first.baseUrl, languageCode: first.languageCode };
}

export function releaseAutoFetch(tabId: number): void {
  const state = tabs.get(tabId);
  if (state) state.autoFetching = false;
}

export function takeIfReady(
  tabId: number,
  options: { force?: boolean } = {},
): TranscriptResponse | null {
  const state = tabs.get(tabId);
  if (!state || !state.videoId) return null;
  if (!state.segments || state.segments.length === 0) return null;

  // Without a player snapshot we can still emit using fallbacks.
  const player = state.player;
  const language = player?.language ?? "en";
  const title = player?.title ?? state.videoId;
  const tracks = player?.tracks ?? [];
  const isAutoGenerated = player?.isAutoGenerated ?? false;
  const chapters: Chapter[] = player ? parseChapters(player.shortDescription) : [];

  const response: TranscriptResponse = {
    videoId: state.videoId,
    title,
    language,
    isAutoGenerated,
    tracks,
    segments: state.segments,
    ...(chapters.length > 0 && { chapters }),
  };

  if (!options.force && state.emittedFor === state.videoId) return null;
  state.emittedFor = state.videoId;
  return response;
}
